# Generated by Django 5.1.4 on 2026-01-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='leaseflex_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Leaseflex ID'),
        ),
    ]
