# Generated by Django 5.1.4 on 2026-04-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_leaseflex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
    ]
