# Generated by Django 5.2.14 on 2026-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_authevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
