# Generated by Django 5.1.4 on 2025-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistperson',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='blacklistperson',
            name='tc_vkn_passport_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TC/VKN/Passport No'),
        ),
    ]
