# Generated by Django 5.1.4 on 2025-09-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_blacklistperson_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistperson',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='blacklistperson',
            name='tc_vkn_passport_no',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='TC/VKN/Passport No'),
        ),
    ]
