# Generated by Django 5.1.4 on 2025-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_blacklistperson_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistperson',
            name='other_names',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Other Names'),
        ),
    ]
