# Generated by Django 5.1.4 on 2025-09-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_alter_blacklistperson_other_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistperson',
            name='other_names',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Other Names'),
        ),
    ]
