# Generated by Django 5.1.4 on 2025-09-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_alter_blacklistperson_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistperson',
            name='birthday',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='blacklistperson',
            name='nationality',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Nationality'),
        ),
    ]
