# Generated by Django 5.1.4 on 2025-09-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0008_blacklistperson_birthday_blacklistperson_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistperson',
            name='birthday',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Birthday'),
        ),
    ]
