# Generated by Django 5.1.4 on 2025-09-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0009_alter_blacklistperson_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistperson',
            name='date_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Date/Number'),
        ),
        migrations.AddField(
            model_name='blacklistperson',
            name='organization',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Organization'),
        ),
    ]
