# Generated by Django 5.1.4 on 2025-11-05 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('compliance', '0010_blacklistperson_date_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('tc_vkn_no', models.CharField(blank=True, max_length=500, null=True, verbose_name='TC/VKN No')),
                ('is_reliable_person', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_persons', to='companies.company')),
            ],
        ),
    ]
