# Generated by Django 5.1.4 on 2025-11-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0011_thirdperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdperson',
            name='is_reliable_person',
        ),
        migrations.AddField(
            model_name='thirdperson',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged')], default='pending', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
