# Generated by Django 5.1.4 on 2025-11-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0013_thirdperson_bank_activities'),
        ('leasing', '0050_lease_first_installment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdperson',
            name='bank_activities',
            field=models.ManyToManyField(blank=True, related_name='bank_activities_third_persons', to='leasing.bankactivity'),
        ),
    ]
