# Generated by Django 5.1.4 on 2025-11-19 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('compliance', '0015_thirdperson_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPersonDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('label', models.CharField(blank=True, max_length=250, null=True, verbose_name='Label')),
                ('file', models.FileField(blank=True, help_text='Please upload a file.', null=True, upload_to='media/docs/compliance/third_person/documents/', verbose_name='File')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_person_documents', to='companies.company')),
            ],
        ),
    ]
