# Generated by Django 5.1.4 on 2025-11-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0016_thirdpersondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpersondocument',
            name='third_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_person_third_person_documents', to='compliance.thirdperson'),
        ),
    ]
