# Generated by Django 5.1.4 on 2025-11-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0017_thirdpersondocument_third_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpersondocument',
            name='file',
            field=models.FileField(blank=True, help_text='Please upload a file.', null=True, upload_to='docs/compliance/third_person/documents/', verbose_name='File'),
        ),
    ]
