# Generated by Django 5.1.4 on 2025-11-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0018_alter_thirdpersondocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdperson',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged'), ('documented', 'Documented')], default='pending', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
