# Generated by Django 5.1.4 on 2025-12-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0020_alter_thirdperson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdperson',
            name='is_vpos',
            field=models.BooleanField(default=False),
        ),
    ]
