# Generated by Django 5.1.4 on 2025-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0021_thirdperson_is_vpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdperson',
            name='is_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
