# Generated by Django 5.1.4 on 2025-12-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0022_thirdperson_is_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdperson',
            name='is_customer_sent',
            field=models.BooleanField(default=False),
        ),
    ]
