# Generated by Django 5.1.4 on 2026-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0023_thirdperson_is_customer_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdperson',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Card No'),
        ),
    ]
