# Generated by Django 5.2.14 on 2026-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0025_thirdperson_customer_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdperson',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged'), ('need_document', 'Need Document'), ('collection_denied', 'Collection Denied')], default='pending', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
