# Generated by Django 5.1.4 on 2025-08-06 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('project_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Project ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('comission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Comission Rate')),
                ('term_diff_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Term Diff Rate')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='companies.company')),
            ],
        ),
    ]
