# Generated by Django 5.1.4 on 2025-08-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Vendor ID'),
        ),
    ]
