# Generated by Django 5.1.4 on 2025-08-06 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0032_alter_partner_types'),
        ('projects', '0002_project_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_projects', to='partners.partner'),
        ),
    ]
