# Generated by Django 5.1.4 on 2025-10-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='real_estate_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Real Estate ID'),
        ),
    ]
