# Generated by Django 5.1.4 on 2025-10-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_realestate_real_estate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='parcel',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Parcel'),
        ),
    ]
