# Generated by Django 5.1.4 on 2025-10-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_titledead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titledead',
            name='ada',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Ada'),
        ),
        migrations.AlterField(
            model_name='titledead',
            name='parsel',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Parsel'),
        ),
    ]
