# Generated by Django 5.1.4 on 2025-10-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_titledead_ada_alter_titledead_parsel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TitleDead',
        ),
    ]
