# Generated by Django 5.1.4 on 2025-10-31 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('projects', '0010_delete_titledead'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleDeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tasinmaz_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Taşınmaz No')),
                ('nitelik', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nitelik')),
                ('il', models.CharField(blank=True, max_length=25, null=True, verbose_name='İl')),
                ('ilce', models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe')),
                ('mahalle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mahalle')),
                ('yuzolcum', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Yüzölçüm')),
                ('ada', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ada')),
                ('parsel', models.CharField(blank=True, max_length=25, null=True, verbose_name='Parsel')),
                ('unit', models.CharField(blank=True, max_length=25, null=True, verbose_name='Unit')),
                ('zemin_hisse_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zemin Hisse ID')),
                ('zemin_tipi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zemin Tipi')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_deads', to='companies.company')),
            ],
        ),
    ]
