# Generated by Django 5.1.4 on 2026-05-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='bbsn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='BBSN'),
        ),
    ]
