# Generated by Django 5.1.4 on 2025-09-02 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0013_exportprocess_export_url'),
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinmaksBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('bank_account_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Account Id')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('account_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account No')),
                ('branch_code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Branch Code')),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Branch Name')),
                ('finmaks_account_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Finmaks Account Type')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Available Balance')),
                ('over_draft', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Over Draft')),
                ('credit_risk', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Credit Risk')),
                ('blocked_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Blocked Balance')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Credit Limit')),
                ('currency_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Currency Type')),
                ('bank_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Name')),
                ('bank_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Code')),
                ('bank_integration_info_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Integration Info Id')),
                ('last_read_time', models.DateTimeField(blank=True, null=True, verbose_name='Last Read Time')),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_bank_accounts', to='common.currency')),
            ],
        ),
    ]
