# Generated by Django 5.1.4 on 2025-09-02 12:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmaksbankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_bank_accounts', to='companies.company'),
        ),
        migrations.CreateModel(
            name='FinmaksTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Id')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Transaction Date')),
                ('explanation_field', models.CharField(blank=True, max_length=500, null=True, verbose_name='Explanation Field')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('sender_vkn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Sender VKN')),
                ('sender_iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sender IBAN')),
                ('SenderAccountName', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Id')),
                ('receiver_vkn', models.CharField(blank=True, max_length=25, null=True, verbose_name='Receiver VKN')),
                ('receiver_iban', models.CharField(blank=True, max_length=25, null=True, verbose_name='Receiver IBAN')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Receipt Number')),
                ('value_date', models.DateTimeField(blank=True, null=True, verbose_name='Value Date')),
                ('transaction_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Type')),
                ('bank_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Code')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance')),
                ('firm_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Firm Id')),
                ('firm_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Firm Name')),
                ('firm_merchantId', models.CharField(blank=True, max_length=25, null=True, verbose_name='Firm Merchant Id')),
                ('firm_externalCode', models.CharField(blank=True, max_length=25, null=True, verbose_name='Firm External Code')),
                ('firm_externalId', models.CharField(blank=True, max_length=25, null=True, verbose_name='Firm ExternalId')),
                ('transaction_branch_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Branch Code')),
                ('transaction_branch_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Branch Name')),
                ('firm_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Firm Code')),
                ('currency_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Currency Type')),
                ('debit', models.CharField(blank=True, max_length=25, null=True, verbose_name='Debit')),
                ('branch_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Branch Code')),
                ('transaction_external_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction External Id')),
                ('external_id_used', models.BooleanField(default=False)),
                ('external_bank_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='External Bank Id')),
                ('reference_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Reference No')),
                ('finmaks_process_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Finmaks Process Type')),
                ('category_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Category Name')),
                ('integration_field_value', models.CharField(blank=True, max_length=25, null=True, verbose_name='Category Name')),
                ('transaction_status', models.CharField(blank=True, max_length=25, null=True, verbose_name='Transaction Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_bank_account_finmaks_transactions', to='finance.finmaksbankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_transactions', to='companies.company')),
            ],
        ),
    ]
