# Generated by Django 5.1.4 on 2025-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_finmaksbankaccount_company_finmakstransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finmakstransaction',
            name='SenderAccountName',
        ),
        migrations.AddField(
            model_name='finmakstransaction',
            name='sender_account_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='SenderAccountName'),
        ),
    ]
