# Generated by Django 5.1.4 on 2025-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_finmakstransaction_senderaccountname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmakstransaction',
            name='receiver_iban',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Receiver IBAN'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='receiver_vkn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Receiver VKN'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='sender_account_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SenderAccountName'),
        ),
    ]
