# Generated by Django 5.1.4 on 2025-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_finmakstransaction_receiver_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finmaksbankaccount',
            name='finekra_bank_account_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Finekra Bank Account Id'),
        ),
    ]
