# Generated by Django 5.1.4 on 2025-10-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_finmaksbankaccount_finekra_bank_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finmaksbankaccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
