# Generated by Django 5.1.4 on 2025-11-13 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_finmaksbankaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmakstransaction',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_bank_account_finmaks_transactions', to='finance.finmaksbankaccount'),
        ),
    ]
