# Generated by Django 5.1.4 on 2025-12-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_finmakstransaction_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmakstransaction',
            name='category_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='firm_externalCode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firm External Code'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='firm_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firm Name'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='integration_field_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='transaction_branch_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Branch Code'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='transaction_branch_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Branch Name'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Status'),
        ),
    ]
