# Generated by Django 5.1.4 on 2025-12-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_finmakstransaction_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmakstransaction',
            name='branch_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch Code'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='debit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Debit'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='finmaks_process_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finmaks Process Type'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='firm_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firm Code'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference No'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='sender_vkn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sender VKN'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Type'),
        ),
    ]
