# Generated by Django 5.1.4 on 2025-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_finmakstransaction_branch_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmakstransaction',
            name='bank_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Code'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='currency_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency Type'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='external_bank_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='External Bank Id'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='firm_externalId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firm ExternalId'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='firm_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firm Id'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='firm_merchantId',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Firm Merchant Id'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='transaction_external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction External Id'),
        ),
        migrations.AlterField(
            model_name='finmakstransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Transaction Id'),
        ),
    ]
