# Generated by Django 5.1.4 on 2025-12-25 14:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('finance', '0010_alter_finmakstransaction_bank_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinmaksBankAccountDailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Available Balance')),
                ('over_draft', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Over Draft')),
                ('credit_risk', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Credit Risk')),
                ('blocked_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Blocked Balance')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Credit Limit')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_bank_account_daily_records', to='companies.company')),
                ('finmaks_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_bank_account_finmaks_bank_account_daily_records', to='finance.finmaksbankaccount')),
            ],
        ),
    ]
