# Generated by Django 5.1.4 on 2026-01-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_finmaksbankaccountdailyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='finmakstransaction',
            name='is_vpos',
            field=models.BooleanField(default=False),
        ),
    ]
