# Generated by Django 5.1.4 on 2026-02-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_vpostransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finmakstransaction',
            name='sender_account_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='SenderAccountName'),
        ),
    ]
