# Generated by Django 5.1.4 on 2026-03-23 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_tuferate_value'),
        ('finance', '0014_alter_finmakstransaction_sender_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpostransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_vpos_transactions', to='common.currency'),
        ),
    ]
