# Generated by Django 5.1.4 on 2026-03-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_vpostransaction_amount_vpostransaction_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpostransaction',
            old_name='amount',
            new_name='paid_amount',
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='adres',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='firma_adi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='ilce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='kurum_tipi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Kurum Tipi'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='lease_posting_group_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='musteri_tipi',
            field=models.PositiveIntegerField(default=0, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='posta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posta'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='process_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Process Date'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='sehir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='ulke',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ülke'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='vergi_dairesi',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='vergi_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='web_sitesi',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Web Sitesi'),
        ),
    ]
