# Generated by Django 5.1.4 on 2026-03-24 09:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('finance', '0016_rename_amount_vpostransaction_paid_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPosIletisim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('iletisim_turu', models.CharField(blank=True, max_length=50, null=True)),
                ('iletisim_degeri', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, choices=[('bireysel', 'Bireysel'), ('kurumsal', 'Kurumsal')], default='bireysel', max_length=25, null=True, verbose_name='Type')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpos_iletisims', to='companies.company')),
                ('vpos_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpos_transaction_vpos_iletisims', to='finance.vpostransaction')),
            ],
        ),
    ]
