# Generated by Django 5.1.4 on 2026-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_vposiletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpostransaction',
            name='ad',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='adres_birey',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adres Birey'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='bank_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Code'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='cinsiyet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cinsiyet'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='contract_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Contract Code'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='dogum_tarihi',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='email',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='ext_transaction_id',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='External Transaction ID'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='ikinci_ad',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='İkinci Ad'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='ilce_birey',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe Birey'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='orta_ad',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Orta Ad'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='pasaport_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Pasaport No'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='password',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='posta_birey',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Posta Birey'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='sehir_birey',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şehir Birey'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='soyad',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Soyad'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='tc_kimlik_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='TC Kimlik No'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='ulke_birey',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Ülke Birey'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='username',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='User Name'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='uyruk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Uyruk'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='vergi_dairesi_birey',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Vergi Dairesi Birey'),
        ),
        migrations.AddField(
            model_name='vpostransaction',
            name='vergi_no_birey',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vergi No Birey'),
        ),
    ]
