# Generated by Django 5.1.4 on 2025-07-01 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeAccount',
        ),
    ]
