# Generated by Django 5.1.4 on 2025-07-01 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0010_alter_status_model_alter_status_name'),
        ('companies', '0005_usercompany_display_currency'),
        ('ledger', '0002_delete_tradeaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account ID')),
                ('code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account Code')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_ledger_accounts', to='common.currency')),
            ],
        ),
    ]
