# Generated by Django 5.1.4 on 2025-07-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_initial'),
        ('partners', '0028_partner_crm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgeraccount',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_ledger_accounts', to='partners.partner'),
        ),
    ]
