# Generated by Django 5.1.4 on 2025-07-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_ledgeraccount_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='code',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Account Code'),
        ),
    ]
