# Generated by Django 5.1.4 on 2025-07-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_ledgeraccount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgeraccount',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Name'),
        ),
    ]
