# Generated by Django 5.1.4 on 2025-06-18 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0009_mainstatus_status'),
        ('companies', '0005_usercompany_display_currency'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Type')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Vat')),
                ('activation_date', models.DateField(blank=True, null=True, verbose_name='Activation Date')),
                ('musteri_baz_maliyet', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Müşteri Baz Maliyet')),
                ('vade', models.IntegerField(default=0, verbose_name='Vade')),
                ('leasing_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Leasing Rate')),
                ('irr', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='IRR')),
                ('project_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Project No')),
                ('leasing_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Leasing Type')),
                ('application_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Application No')),
                ('is_last_project', models.BooleanField(default=False)),
                ('current_request', models.CharField(blank=True, max_length=25, null=True, verbose_name='Current Request')),
                ('finansman_kurum', models.CharField(blank=True, max_length=25, null=True, verbose_name='Finansman Kurum')),
                ('is_tufe', models.BooleanField(default=False)),
                ('is_musterek', models.BooleanField(default=False)),
                ('bbsn', models.CharField(blank=True, max_length=25, null=True, verbose_name='BBSN')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rents', to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcontract_rents', to='contracts.contract')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_rents', to='common.currency')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_rents', to='common.status')),
            ],
        ),
    ]
