# Generated by Django 5.1.4 on 2025-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_status',
            field=models.CharField(blank=True, choices=[('aktiflestirildi', 'Aktifleştirildi'), ('iptal_edildi', 'İptal Edildi'), ('devredildi', 'Devredildi'), ('baskasina_transfer_edildi', 'Başkasına Transfer Edildi'), ('planlandi', 'Planlandı'), ('durduruldu', 'Durduruldu'), ('feshedildi', 'Feshedildi'), ('revize_edildi', 'Revize Edildi'), ('pert', 'Pert'), ('envantere_alindi', 'Envantere Alındı'), ('para_birimi_degisti', 'Para Birimi Değişti'), ('kanuni_takibe_alindi', 'Kanuni Takibe Alındı')], default='aktiflestirildi', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
