# Generated by Django 5.1.4 on 2025-06-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_lease_lease_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='leasing_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Leasing Rate'),
        ),
    ]
