# Generated by Django 5.1.4 on 2025-06-19 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_status_model_alter_status_name'),
        ('companies', '0005_usercompany_display_currency'),
        ('contracts', '0002_alter_contract_kof_tan_sozlesmeye_aktarim_tarihi_and_more'),
        ('leasing', '0003_alter_lease_leasing_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcontract_leases', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_leases', to='common.currency'),
        ),
    ]
