# Generated by Django 5.1.4 on 2025-06-24 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('contracts', '0003_contract_quotation_obj'),
        ('leasing', '0004_alter_lease_company_alter_lease_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_leases', to='contracts.contract'),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Payment Date')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Vat')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid')),
                ('principal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Principal')),
                ('interest', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Interest')),
                ('sequency', models.PositiveIntegerField(default=0, verbose_name='Sequency')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='companies.company')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_installments', to='leasing.lease')),
            ],
        ),
    ]
