# Generated by Django 5.1.4 on 2025-06-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0005_alter_lease_contract_installment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='code',
        ),
    ]
