# Generated by Django 5.1.4 on 2025-07-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0006_remove_installment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue Amount'),
        ),
    ]
