# Generated by Django 5.1.4 on 2025-07-08 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_status_model_alter_status_name'),
        ('companies', '0005_usercompany_display_currency'),
        ('leasing', '0007_installment_overdue_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('bank', models.CharField(blank=True, max_length=140, null=True, verbose_name='Bank')),
                ('bank_account_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Bank Account No')),
                ('process_date', models.DateTimeField(blank=True, null=True, verbose_name='Process Date')),
                ('process_type', models.CharField(blank=True, choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=25, null=True, verbose_name='Process Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('receipt_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Receipt No')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_activities', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_bank_activities', to='common.currency')),
            ],
        ),
    ]
