# Generated by Django 5.1.4 on 2025-07-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0008_bankactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='leaseflex_automation',
            field=models.BooleanField(default=False),
        ),
    ]
