# Generated by Django 5.1.4 on 2025-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0009_lease_leaseflex_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='tc_vkn_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TC/VKN No'),
        ),
    ]
