# Generated by Django 5.1.4 on 2025-07-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0010_bankactivity_tc_vkn_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='leases',
            field=models.ManyToManyField(blank=True, related_name='lease_bank_activities', to='leasing.lease'),
        ),
    ]
