# Generated by Django 5.1.4 on 2025-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0011_bankactivity_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Branch Code'),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='bank_code',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Bank Code'),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='crosss_bank_account_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Cross Bank Account No'),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='crosss_bank_branch_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Cross Bank Branch Code'),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='crosss_bank_code',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Cross Bank Code'),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='kontrat_no',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Kontrat No'),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='process_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Process Code'),
        ),
        migrations.AlterField(
            model_name='bankactivity',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Account No'),
        ),
    ]
