# Generated by Django 5.1.4 on 2025-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0012_bankactivity_bank_branch_code_bankactivity_bank_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='credit_or_debit',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Credit Or Debit'),
        ),
    ]
