# Generated by Django 5.1.4 on 2025-07-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0013_bankactivity_credit_or_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
    ]
