# Generated by Django 5.1.4 on 2025-07-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0014_bankactivity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankactivity',
            old_name='crosss_bank_account_no',
            new_name='cross_bank_account_no',
        ),
        migrations.RenameField(
            model_name='bankactivity',
            old_name='crosss_bank_branch_code',
            new_name='cross_bank_branch_code',
        ),
        migrations.RenameField(
            model_name='bankactivity',
            old_name='crosss_bank_code',
            new_name='cross_bank_code',
        ),
    ]
