# Generated by Django 5.1.4 on 2025-07-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0015_rename_crosss_bank_account_no_bankactivity_cross_bank_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankactivity',
            name='cross_bank_account_no',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Cross Bank Account No'),
        ),
    ]
