# Generated by Django 5.1.4 on 2025-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0016_alter_bankactivity_cross_bank_account_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='processed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Processed Amount'),
        ),
    ]
