# Generated by Django 5.1.4 on 2025-07-12 17:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('leasing', '0017_lease_processed_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankActivityLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('processed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Processed Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('bank_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_activity_bank_acitivity_leases', to='leasing.bankactivity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_activity_leases', to='companies.company')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_bank_acitivity_leases', to='leasing.lease')),
            ],
        ),
    ]
