# Generated by Django 5.1.4 on 2025-07-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0018_bankactivitylease'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='bank_activity_leases',
            field=models.ManyToManyField(blank=True, related_name='bank_activity_lease_bank_activities', to='leasing.lease'),
        ),
    ]
