# Generated by Django 5.1.4 on 2025-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0019_bankactivity_bank_activity_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivitylease',
            name='leaseflex_automation',
            field=models.BooleanField(default=False),
        ),
    ]
