# Generated by Django 5.1.4 on 2025-07-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0020_bankactivitylease_leaseflex_automation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankactivity',
            name='bank_activity_leases',
        ),
    ]
