# Generated by Django 5.1.4 on 2025-07-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0021_remove_bankactivity_bank_activity_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Lease ID'),
        ),
    ]
