# Generated by Django 5.1.4 on 2025-07-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0022_lease_lease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='installment',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Vat Amount'),
        ),
    ]
