# Generated by Django 5.1.4 on 2025-07-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0023_installment_payment_installment_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivitylease',
            name='is_third_person',
            field=models.BooleanField(default=False),
        ),
    ]
