# Generated by Django 5.1.4 on 2025-07-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0024_bankactivitylease_is_third_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='process_date_date',
            field=models.DateField(blank=True, null=True, verbose_name='Process Date Date'),
        ),
    ]
