# Generated by Django 5.1.4 on 2025-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0025_bankactivity_process_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='lease_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lease Type'),
        ),
    ]
