# Generated by Django 5.1.4 on 2025-07-22 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0026_installment_lease_type'),
        ('partners', '0031_alter_partner_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOverdueView',
            fields=[
                ('partner', models.OneToOneField(db_column='partner_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='partners.partner')),
                ('max_overdue_days', models.IntegerField()),
            ],
            options={
                'db_table': 'partner_max_overdue_days',
                'managed': False,
            },
        ),
    ]
