# Generated by Django 5.1.4 on 2025-07-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0029_partneroverdueview'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='overdue_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue Amount'),
        ),
        migrations.AddField(
            model_name='lease',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid'),
        ),
    ]
