# Generated by Django 5.1.4 on 2025-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0030_lease_overdue_amount_lease_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='overdue_days',
            field=models.IntegerField(default=0, verbose_name='Overdue Days'),
        ),
    ]
