# Generated by Django 5.1.4 on 2025-07-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0031_lease_overdue_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_kdv_diff',
            field=models.BooleanField(default=False),
        ),
    ]
