# Generated by Django 5.1.4 on 2025-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0032_lease_is_kdv_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='paid_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid'),
        ),
    ]
