# Generated by Django 5.1.4 on 2025-07-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0033_lease_paid_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Payment'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='paid_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid Rate'),
        ),
    ]
