# Generated by Django 5.1.4 on 2025-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0034_lease_total_payment_alter_lease_paid_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='overdue_0_30',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='lease',
            name='overdue_121_150',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='lease',
            name='overdue_151_180',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='lease',
            name='overdue_181_gte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='lease',
            name='overdue_31_60',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='lease',
            name='overdue_61_90',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
        migrations.AddField(
            model_name='lease',
            name='overdue_91_120',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue'),
        ),
    ]
