# Generated by Django 5.1.4 on 2025-07-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0035_lease_overdue_0_30_lease_overdue_121_150_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='overdue_0_30',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 0 - 30'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='overdue_121_150',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 121 - 150'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='overdue_151_180',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 151 - 180'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='overdue_181_gte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 181 >'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='overdue_31_60',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 31 - 60'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='overdue_61_90',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 61 - 90'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='overdue_91_120',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Overdue 91 - 120'),
        ),
    ]
