# Generated by Django 5.1.4 on 2025-07-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0036_alter_lease_overdue_0_30_alter_lease_overdue_121_150_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
