# Generated by Django 5.1.4 on 2025-07-31 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0037_lease_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
