# Generated by Django 5.1.4 on 2025-08-01 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0038_bankactivity_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankactivitylease',
            name='processed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Processed Amount'),
        ),
    ]
