# Generated by Django 5.1.4 on 2025-08-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0039_alter_bankactivitylease_processed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_agreed_terminated',
            field=models.BooleanField(default=False),
        ),
    ]
