# Generated by Django 5.1.4 on 2025-08-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0040_lease_is_agreed_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_credit',
            field=models.BooleanField(default=False),
        ),
    ]
