# Generated by Django 5.1.4 on 2025-08-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0041_lease_is_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='is_reliable_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankactivity',
            name='is_third_person',
            field=models.BooleanField(default=False),
        ),
    ]
