# Generated by Django 5.1.4 on 2025-09-03 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_finmakstransaction_receiver_iban_and_more'),
        ('leasing', '0042_bankactivity_is_reliable_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='finmaks_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finmaks_transaction_bank_activities', to='finance.finmakstransaction'),
        ),
    ]
