# Generated by Django 5.1.4 on 2025-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0043_bankactivity_finmaks_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Interest Rate'),
        ),
    ]
