# Generated by Django 5.1.4 on 2025-10-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0044_lease_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='is_certain',
            field=models.BooleanField(default=False),
        ),
    ]
