# Generated by Django 5.1.4 on 2025-10-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0045_bankactivity_is_certain'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_status_update_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lease Status Update Date'),
        ),
    ]
