# Generated by Django 5.1.4 on 2025-10-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0046_lease_lease_status_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_under_review',
            field=models.BooleanField(default=False),
        ),
    ]
