# Generated by Django 5.1.4 on 2025-11-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0047_lease_is_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='type',
            field=models.CharField(blank=True, choices=[('1', 'Kira'), ('2', 'Peşinat'), ('3', 'Küçük Kira'), ('4', 'Ödemesiz'), ('5', 'Devir Bedeli'), ('6', 'Reeskont'), ('7', 'Sadece Faiz')], default='1', max_length=25, null=True, verbose_name='Payment Type'),
        ),
    ]
