# Generated by Django 5.1.4 on 2025-11-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0048_installment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance'),
        ),
    ]
