# Generated by Django 5.1.4 on 2025-11-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0049_installment_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='first_installment_date',
            field=models.DateField(blank=True, null=True, verbose_name='First Installment Date'),
        ),
    ]
