# Generated by Django 5.1.4 on 2025-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0050_lease_first_installment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='third_person_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged')], default='pending', max_length=25, null=True, verbose_name='Third Person Status'),
        ),
    ]
