# Generated by Django 5.1.4 on 2025-11-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0051_bankactivity_third_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankactivity',
            name='third_person_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('flagged', 'Flagged'), ('need_document', 'Need Document')], default='pending', max_length=25, null=True, verbose_name='Third Person Status'),
        ),
    ]
