# Generated by Django 5.1.4 on 2025-11-25 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0052_alter_bankactivity_third_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankactivity',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
