# Generated by Django 5.1.4 on 2025-11-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0053_alter_bankactivity_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankactivity',
            name='leases',
            field=models.ManyToManyField(blank=True, editable=False, related_name='lease_bank_activities', to='leasing.lease'),
        ),
    ]
