# Generated by Django 5.1.4 on 2025-12-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0054_alter_bankactivity_leases'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='warning_notice_status',
            field=models.CharField(blank=True, choices=[('ihtar_yok', 'İhtar Yok'), ('normal_ihtar', 'Notrmal İhtar'), ('kapsamli_ihtar', 'Kapsamlı İhtar')], default='ihtar_yok', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
