# Generated by Django 5.1.4 on 2025-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0055_lease_warning_notice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='terminated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Terminated Date'),
        ),
    ]
