# Generated by Django 5.1.4 on 2025-12-11 07:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0056_lease_terminated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='geciken_odenmesi_gereken_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Geciken Ödenmesi Gereken USD'),
        ),
        migrations.AddField(
            model_name='lease',
            name='geciken_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Geciken USD'),
        ),
        migrations.AddField(
            model_name='lease',
            name='kur_kaybi',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Kur Kaybı'),
        ),
        migrations.AddField(
            model_name='lease',
            name='kur_kaybi_yuzde',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Kur Kaybı Yüzde'),
        ),
        migrations.AddField(
            model_name='lease',
            name='odenen_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ödenen USD'),
        ),
        migrations.AddField(
            model_name='lease',
            name='odenen_yerel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ödenen Yerel'),
        ),
        migrations.AddField(
            model_name='lease',
            name='odenmesi_gereken_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ödenmesi Gereken USD'),
        ),
        migrations.AddField(
            model_name='lease',
            name='odenmesi_gereken_yerel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Ödenmesi Gereken Yerel'),
        ),
    ]
