# Generated by Django 5.1.4 on 2025-12-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0057_lease_geciken_odenmesi_gereken_usd_lease_geciken_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='main_lease_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Main Lease ID'),
        ),
    ]
