# Generated by Django 5.1.4 on 2025-12-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_item_item_group_code_and_more'),
        ('leasing', '0058_lease_main_lease_id'),
        ('partners', '0037_partner_birth_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_leases', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='lease',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_leases', to='partners.partner'),
        ),
    ]
