# Generated by Django 5.1.4 on 2025-12-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0059_lease_item_lease_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='transfer_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Transfer Count'),
        ),
    ]
