# Generated by Django 5.1.4 on 2025-12-22 20:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0060_lease_transfer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tufeli_geciken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfeli Geciken'),
        ),
    ]
