# Generated by Django 5.1.4 on 2025-12-29 21:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0061_lease_tufeli_geciken'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tufe_endeks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Endeks'),
        ),
    ]
