# Generated by Django 5.1.4 on 2025-12-31 05:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0062_lease_tufe_endeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tufe_ana_endeks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Ana Endeks'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tufe_fark',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Fark'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tufe_reel_fark',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Reel Fark'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tufe_tahsilat_endeks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Tahsilat Endeks'),
        ),
    ]
