# Generated by Django 5.1.4 on 2026-01-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0063_lease_tufe_ana_endeks_lease_tufe_fark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='installment_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Installment ID'),
        ),
    ]
