# Generated by Django 5.1.4 on 2026-01-13 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0064_installment_installment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='tufe_odenen',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Ödenen'),
        ),
        migrations.AddField(
            model_name='lease',
            name='tufe_odenmesi_gereken',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Tüfe Ödenmesi Gereken'),
        ),
    ]
