# Generated by Django 5.1.4 on 2026-01-14 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0065_lease_tufe_odenen_lease_tufe_odenmesi_gereken'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='notary_public_date',
            field=models.DateField(blank=True, null=True, verbose_name='Notary Public Date'),
        ),
    ]
