# Generated by Django 5.1.4 on 2026-01-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0066_lease_notary_public_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='block',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Block'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit'),
        ),
    ]
