# Generated by Django 5.1.4 on 2026-01-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0067_lease_block_lease_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='parcel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parcel'),
        ),
    ]
