# Generated by Django 5.1.4 on 2026-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0068_lease_parcel'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='island',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Island'),
        ),
    ]
