# Generated by Django 5.1.4 on 2026-01-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0069_lease_island'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='lease',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='District'),
        ),
    ]
