# Generated by Django 5.1.4 on 2026-01-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0070_lease_city_lease_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='is_vpos',
            field=models.BooleanField(default=False),
        ),
    ]
