# Generated by Django 5.1.4 on 2026-01-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0071_bankactivity_is_vpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Card No'),
        ),
    ]
