# Generated by Django 5.1.4 on 2026-01-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0072_bankactivity_card_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='crm_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM No'),
        ),
    ]
