# Generated by Django 5.1.4 on 2026-01-26 14:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0073_lease_crm_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='ifs_tahsilat',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='IFS Tahsilat'),
        ),
    ]
