# Generated by Django 5.1.4 on 2026-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0074_lease_ifs_tahsilat'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
    ]
