# Generated by Django 5.1.4 on 2026-02-04 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0075_lease_is_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='is_invoice',
            new_name='is_not_invoice',
        ),
    ]
