# Generated by Django 5.1.4 on 2026-03-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0076_rename_is_invoice_lease_is_not_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_last_project_arinet',
            field=models.BooleanField(default=False),
        ),
    ]
