# Generated by Django 5.1.4 on 2026-03-17 12:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0077_lease_is_last_project_arinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Paid Amount'),
        ),
    ]
