# Generated by Django 5.1.4 on 2026-03-18 08:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0078_lease_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='installment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Total Installment Amount'),
        ),
        migrations.AddField(
            model_name='lease',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Transfer Amount'),
        ),
    ]
