# Generated by Django 5.1.4 on 2026-03-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0079_lease_installment_amount_lease_transfer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankactivity',
            name='is_title_deed_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
