# Generated by Django 5.1.4 on 2026-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0080_bankactivity_is_title_deed_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankactivity',
            name='is_title_deed_delivered',
        ),
        migrations.AddField(
            model_name='lease',
            name='is_title_deed_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
