# Generated by Django 5.1.4 on 2026-03-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0081_remove_bankactivity_is_title_deed_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
