# Generated by Django 5.1.4 on 2026-04-06 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0083_leasenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='purchase_document_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Purchase Document Amount'),
        ),
    ]
