# Generated by Django 5.1.4 on 2026-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0084_lease_purchase_document_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='crm_contract_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM Contract Code'),
        ),
    ]
