# Generated by Django 5.1.4 on 2026-04-10 08:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0085_lease_crm_contract_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='crm_bbsn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM BBSN'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_durum',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM Durum'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='CRM Invoice Amount'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='CRM Invoice Date'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_invoice_kdv_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='CRM Invoice KDV Amount'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_invoice_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CRM Invoice No'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_invoice_total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='CRM Invoice Total Amount'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_project_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM Project ID'),
        ),
        migrations.AddField(
            model_name='lease',
            name='crm_satici',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='CRM Satici'),
        ),
    ]
