# Generated by Django 5.1.4 on 2026-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0086_lease_crm_bbsn_lease_crm_durum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='ari_bbsn',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Arı BBSN'),
        ),
    ]
