# Generated by Django 5.1.4 on 2026-04-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0087_lease_ari_bbsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='period',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Period'),
        ),
    ]
