# Generated by Django 5.1.4 on 2026-04-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0088_lease_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_lop_revision',
            field=models.BooleanField(default=False),
        ),
    ]
