# Generated by Django 5.1.4 on 2026-05-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0090_lease_risk_status'),
        ('projects', '0013_realestate_bbsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_leases', to='projects.realestate'),
        ),
    ]
