# Generated by Django 5.1.4 on 2026-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0091_lease_real_estate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='risk_status',
            field=models.CharField(blank=True, choices=[('risk_yok', 'Risk Yok'), ('gecikmede', 'Gecikmede'), ('ihtar_cekilecek', 'İhtar Çekilecek'), ('ihtar_cekildi', 'İhtar Çekildi'), ('fesih_edilecek', 'Fesih Edilecek')], default='risk_yok', max_length=25, null=True, verbose_name='Risk Status'),
        ),
    ]
