# Generated by Django 5.1.4 on 2026-05-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0092_alter_lease_risk_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Signature Date'),
        ),
    ]
