# Generated by Django 5.2.14 on 2026-07-16 12:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0093_lease_signature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='operasyon_baz_maliyet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Operasyon Baz Maliyet'),
        ),
    ]
