# Generated by Django 5.2.14 on 2026-07-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0094_lease_operasyon_baz_maliyet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='lease_id',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Lease ID'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='main_lease_id',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Main Lease ID'),
        ),
    ]
