# Generated by Django 5.2.14 on 2026-07-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0095_alter_lease_lease_id_alter_lease_main_lease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='source_lease_id',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Source Lease ID'),
        ),
    ]
