# Generated by Django 5.2.14 on 2026-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0096_lease_source_lease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='is_terminated_date_manual',
            field=models.BooleanField(default=False),
        ),
    ]
