# Generated by Django 5.1.4 on 2025-06-18 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_city_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, choices=[('contract', 'Contract'), ('rent', 'Rent'), ('invoice', 'Invoice'), ('incoming_request', 'Incoming Request'), ('insurance_policy', 'Insurance Policy'), ('lease_purchase_document', 'Lease Purchase Document'), ('lease_purchase_order', 'Lease Purchase Order'), ('lease_purchase_project', 'Lease Purchase Project'), ('lease_operation_project', 'Lease Operation Project'), ('invoop_leasingice', 'Op Leasing'), ('quotation', 'Quotation'), ('rpr_quo', 'RPR QUO'), ('trade_guarantee', 'Trade Guarantee')], default='contract', max_length=25, null=True, verbose_name='Model')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('main_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_status_statusses', to='common.mainstatus')),
            ],
        ),
    ]
