# Generated by Django 5.1.4 on 2025-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_mainstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='model',
            field=models.CharField(blank=True, choices=[('contract', 'Contract'), ('credit', 'Credit'), ('invoice', 'Invoice'), ('incoming_request', 'Incoming Request'), ('insurance_policy', 'Insurance Policy'), ('lease_purchase_document', 'Lease Purchase Document'), ('lease_purchase_order', 'Lease Purchase Order'), ('lease_purchase_project', 'Lease Purchase Project'), ('lease_operation_project', 'Lease Operation Project'), ('op_leasing', 'Op Leasing'), ('quotation', 'Quotation'), ('rpr_quo', 'RPR QUO'), ('trade_guarantee', 'Trade Guarantee')], default='contract', max_length=25, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Name'),
        ),
    ]
