# Generated by Django 5.1.4 on 2025-07-10 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_status_model_alter_status_name'),
        ('companies', '0005_usercompany_display_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=140, verbose_name='Model Name')),
                ('task_id', models.CharField(max_length=250, unique=True, verbose_name='Task ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=25, null=True, verbose_name='Status')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Items Count')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_processes', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_export_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
