# Generated by Django 5.1.4 on 2025-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_exportprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprocess',
            name='file_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='File Name'),
        ),
    ]
