# Generated by Django 5.1.4 on 2025-07-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_exportprocess_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportprocess',
            name='export_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Export Url'),
        ),
    ]
