# Generated by Django 5.1.4 on 2025-11-02 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_exportprocess_export_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('forex_buying', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Forex Buying')),
                ('forex_selling', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Forex Selling')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_exchange_rates', to='common.currency')),
            ],
        ),
    ]
