# Generated by Django 5.1.4 on 2025-11-02 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_exchangerate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerate',
            name='currency',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_currency_exchange_rates', to='common.currency'),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='target_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_currency_exchange_rates', to='common.currency'),
        ),
    ]
