# Generated by Django 5.1.4 on 2025-12-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_remove_exchangerate_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TufeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Rate')),
                ('change_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Change Rate')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
