# Generated by Django 5.1.4 on 2025-12-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_tuferate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuferate',
            name='code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Code'),
        ),
    ]
