# Generated by Django 5.1.4 on 2025-12-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_tuferate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuferate',
            name='daily_mean',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Daily Mean'),
        ),
    ]
