# Generated by Django 5.1.4 on 2025-12-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_tuferate_daily_mean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuferate',
            name='daily_mean',
        ),
    ]
