# Generated by Django 5.1.4 on 2025-12-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_remove_tuferate_daily_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuferate',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Value'),
        ),
    ]
