# Generated by Django 5.1.4 on 2026-03-31 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_tuferate_value'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('object_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Object UUID')),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Object Representation')),
                ('extra_data', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('session_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Session Key')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_type_user_activities', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_date'], name='common_user_user_id_e2aa86_idx'), models.Index(fields=['content_type', 'object_id'], name='common_user_content_d33a31_idx'), models.Index(fields=['action', 'created_date'], name='common_user_action_f9e481_idx')],
            },
        ),
    ]
