# Generated by Django 5.1.4 on 2025-06-18 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0009_mainstatus_status'),
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0027_alter_partner_address_alter_partner_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('kof', models.CharField(blank=True, max_length=25, null=True, verbose_name='Kof')),
                ('quotation', models.CharField(blank=True, max_length=25, null=True, verbose_name='Quotation')),
                ('committe', models.CharField(blank=True, max_length=25, null=True, verbose_name='Committe')),
                ('credit_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Credit Type')),
                ('customer_representative', models.CharField(blank=True, max_length=140, null=True, verbose_name='Customer Representative')),
                ('supplier', models.CharField(blank=True, max_length=140, null=True, verbose_name='Supplier')),
                ('project', models.CharField(blank=True, max_length=250, null=True, verbose_name='Project')),
                ('mkk_tesciline_gonderilecek_mi', models.BooleanField(default=False)),
                ('kof_tan_sozlesmeye_aktarim_tarihi', models.DateField(blank=True, null=True, verbose_name="Kof'tan Sözleşmeye Aktarım Tarihi")),
                ('lop_open_date', models.DateField(blank=True, null=True, verbose_name='Lop Open Date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_contracts', to='partners.partner')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_contracts', to='common.status')),
            ],
        ),
    ]
