# Generated by Django 5.1.4 on 2025-06-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='kof_tan_sozlesmeye_aktarim_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Kof'tan Sözleşmeye Aktarım Tarihi"),
        ),
        migrations.AlterField(
            model_name='contract',
            name='lop_open_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lop Open Date'),
        ),
    ]
