# Generated by Django 5.1.4 on 2025-06-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_kof_tan_sozlesmeye_aktarim_tarihi_and_more'),
        ('quotations', '0003_quickquotation_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='quotation_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_contracts', to='quotations.quotation'),
        ),
    ]
