# Generated by Django 5.1.4 on 2025-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_quotation_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Contract ID'),
        ),
    ]
