# Generated by Django 5.1.4 on 2025-07-23 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_exportprocess'),
        ('companies', '0005_usercompany_display_currency'),
        ('contracts', '0004_contract_contract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('trn_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Trn ID')),
                ('trn_from_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Trn From ID')),
                ('ledger_account_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ledger Account ID')),
                ('ledger_account_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ledger Account Name')),
                ('trade_account_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Trade Account Code')),
                ('type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Type')),
                ('posting_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Posting Type')),
                ('group_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Group Name')),
                ('account_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account Code')),
                ('account_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Account Name')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('local_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Local Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Exchange Rate')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('user_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='User Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contract_payments', to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_contract_payments', to='contracts.contract')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_contract_payments', to='common.currency')),
            ],
        ),
    ]
