# Generated by Django 5.1.4 on 2025-07-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contractpayment',
            name='local_amount',
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Credit Amount'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='debit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Debit Amount'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='local_credit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Local Credit Amount'),
        ),
        migrations.AddField(
            model_name='contractpayment',
            name='local_debit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Local Debit Amount'),
        ),
    ]
