# Generated by Django 5.1.4 on 2025-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_remove_contractpayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
