# Generated by Django 5.1.4 on 2025-07-24 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_exportprocess'),
        ('contracts', '0008_warningnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_contracts', to='common.currency'),
        ),
    ]
