# Generated by Django 5.1.4 on 2025-07-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_contract_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='warningnotice',
            name='daily_wages_date',
            field=models.DateField(blank=True, null=True, verbose_name='Daily Wages Date'),
        ),
    ]
