# Generated by Django 5.1.4 on 2025-08-07 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_warningnotice_daily_wages_date'),
        ('projects', '0003_remove_project_vendor_id_project_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='project_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contracts', to='projects.project'),
        ),
    ]
