# Generated by Django 5.1.4 on 2025-08-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_contract_project_obj'),
        ('partners', '0032_alter_partner_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_contracts', to='partners.partner'),
        ),
    ]
