# Generated by Django 5.1.4 on 2025-09-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_contract_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='operation_status',
            field=models.CharField(blank=True, choices=[('tedarikcide', 'Tedarikçide'), ('islemde', 'İşlemde'), ('arsivde', 'Arşivde')], default='tedarikcide', max_length=25, null=True, verbose_name='Operation Status'),
        ),
    ]
