# Generated by Django 5.1.4 on 2025-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_contract_operation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='created_date_leaseflex',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created Date Leaseflex'),
        ),
    ]
