# Generated by Django 5.1.4 on 2026-01-19 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('contracts', '0014_contract_created_date_leaseflex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveWarningNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('document_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Document ID')),
                ('risk_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Risk ID')),
                ('customer_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer ID')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Debit Amount')),
                ('daily_wages_date', models.DateField(blank=True, null=True, verbose_name='Daily Wages Date')),
                ('process_start_date', models.DateField(blank=True, null=True, verbose_name='Process Start Date')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Service Date')),
                ('official_cancellation_date', models.DateField(blank=True, null=True, verbose_name='Official Cancellation Date')),
                ('paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Paid')),
                ('diff', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Diff')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('approval_state', models.CharField(blank=True, max_length=250, null=True, verbose_name='Approval State')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_comprehensive_warning_notices', to='companies.company')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_comprehensive_warning_notices', to='contracts.contract')),
            ],
        ),
    ]
