# Generated by Django 5.1.4 on 2026-01-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_comprehensivewarningnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractpayment',
            name='source_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Source Type'),
        ),
    ]
