# Generated by Django 5.1.4 on 2026-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0017_terminationwarningnotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminationwarningnotice',
            old_name='debit_amount',
            new_name='deduction_amount',
        ),
        migrations.RemoveField(
            model_name='terminationwarningnotice',
            name='approval_state',
        ),
        migrations.RemoveField(
            model_name='terminationwarningnotice',
            name='diff',
        ),
        migrations.RemoveField(
            model_name='terminationwarningnotice',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='terminationwarningnotice',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='terminationwarningnotice',
            name='state',
        ),
        migrations.AddField(
            model_name='terminationwarningnotice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Debit Amount'),
        ),
    ]
