# Generated by Django 5.2.14 on 2026-06-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0019_committeeform'),
        ('partners', '0081_partner_nace_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeform',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_committee_forms', to='partners.partner'),
        ),
    ]
