# Generated by Django 5.2.14 on 2026-06-17 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0020_committeeform_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeform',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_committee_forms', to='contracts.contract'),
        ),
    ]
