# Generated by Django 5.2.14 on 2026-07-09 06:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('contracts', '0021_alter_committeeform_contract'),
        ('partners', '0081_partner_nace_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('label', models.CharField(blank=True, max_length=250, null=True, verbose_name='Label')),
                ('file', models.FileField(blank=True, help_text='Please upload a file.', null=True, upload_to='docs/contracts/contract/documents/', verbose_name='File')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_documents', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_contract_documents', to='partners.partner')),
            ],
        ),
    ]
