# Generated by Django 5.2.14 on 2026-07-13 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0022_contractdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractdocument',
            name='partner',
        ),
        migrations.AddField(
            model_name='contractdocument',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_contract_documents', to='contracts.contract'),
        ),
    ]
