# Generated by Django 5.2.14 on 2026-07-15 17:14

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0023_remove_contractdocument_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdocument',
            name='file',
            field=models.FileField(blank=True, help_text='Please upload a file.', null=True, upload_to=contracts.models.contract_document_upload_path, verbose_name='File'),
        ),
    ]
