# Generated by Django 5.2.14 on 2026-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0024_alter_contractdocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Departure Date'),
        ),
    ]
