# Generated by Django 5.1.4 on 2025-06-16 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0020_alter_partner_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='vat_no',
        ),
        migrations.AddField(
            model_name='partner',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='partner',
            name='customer_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer Code'),
        ),
        migrations.AddField(
            model_name='partner',
            name='father_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Father Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='first_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_turkkep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='kep',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Kep'),
        ),
        migrations.AddField(
            model_name='partner',
            name='kep_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kep Expiry Date'),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='partner',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport No'),
        ),
        migrations.AddField(
            model_name='partner',
            name='tc_vkn_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TC/VKN No'),
        ),
        migrations.AddField(
            model_name='partner',
            name='ticari_sicil_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ticari Sicil No'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('main_sector_code', models.CharField(max_length=50, verbose_name='Main Sector Code')),
                ('match_code', models.CharField(max_length=50, verbose_name='Match Code')),
                ('kkbmb_sector_code', models.CharField(max_length=50, verbose_name='KKBMB Sector Code')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='companies.company')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_partners', to='partners.sector'),
        ),
    ]
