# Generated by Django 5.1.4 on 2025-06-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0021_remove_partner_vat_no_partner_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='tc_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TC No'),
        ),
        migrations.AddField(
            model_name='partner',
            name='vat_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Vat No'),
        ),
    ]
