# Generated by Django 5.1.4 on 2025-06-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0022_partner_tc_no_partner_vat_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='kkbmb_sector_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='KKBMB Sector Code'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='main_sector_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Sector Code'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='match_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Match Code'),
        ),
    ]
