# Generated by Django 5.1.4 on 2025-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0023_alter_sector_kkbmb_sector_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
