# Generated by Django 5.1.4 on 2025-06-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0024_alter_sector_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Partner Name'),
        ),
    ]
