# Generated by Django 5.1.4 on 2025-06-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0025_alter_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='formal_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Partner Formal Name'),
        ),
    ]
