# Generated by Django 5.1.4 on 2025-06-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0026_alter_partner_formal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address2',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Address 2'),
        ),
    ]
