# Generated by Django 5.1.4 on 2025-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0027_alter_partner_address_alter_partner_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='crm_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM Code'),
        ),
    ]
