# Generated by Django 5.1.4 on 2025-07-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0028_partner_crm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='customer_types',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('institutional', 'Institutional')], default='individual', max_length=25, null=True, verbose_name='Customer Type'),
        ),
    ]
