# Generated by Django 5.1.4 on 2025-07-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0029_partner_customer_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='customer_types',
            new_name='customer_type',
        ),
    ]
