# Generated by Django 5.1.4 on 2025-07-18 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0030_rename_customer_types_partner_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('shareholder', 'Shareholder'), ('special', 'Special')], max_length=25, verbose_name='Status'), blank=True, default=list, null=True, size=None),
        ),
    ]
