# Generated by Django 5.1.4 on 2025-07-28 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0031_alter_partner_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('shareholder', 'Shareholder'), ('special', 'Special'), ('barter', 'Barter'), ('virman', 'Virman')], max_length=25, verbose_name='Status'), blank=True, default=list, null=True, size=None),
        ),
    ]
