# Generated by Django 5.1.4 on 2025-09-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0033_alter_partner_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Advance Amount'),
        ),
    ]
