# Generated by Django 5.1.4 on 2025-09-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0034_partner_advance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_reliable_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_scan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='last_scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Scan Date'),
        ),
        migrations.AddField(
            model_name='partner',
            name='next_scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Next Scan Date'),
        ),
    ]
