# Generated by Django 5.1.4 on 2025-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0035_partner_is_reliable_person_partner_is_scan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_commercial',
            field=models.BooleanField(default=False),
        ),
    ]
