# Generated by Django 5.1.4 on 2025-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0036_partner_is_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='birth_place',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Birth Place'),
        ),
    ]
