# Generated by Django 5.1.4 on 2025-12-31 07:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0037_partner_birth_place'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('title', models.CharField(blank=True, max_length=140, null=True, verbose_name='Title')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Text')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_notes', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_partner_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
