# Generated by Django 5.1.4 on 2025-12-31 08:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0038_partnernote'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnernote',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnernote',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
