# Generated by Django 5.1.4 on 2025-12-31 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0039_partnernote_created_date_partnernote_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnernote',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_notes', to='partners.partner'),
        ),
    ]
