# Generated by Django 5.1.4 on 2026-01-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0040_partnernote_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
    ]
