# Generated by Django 5.1.4 on 2026-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0041_partner_is_pep'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='pep_degree',
            field=models.CharField(blank=True, choices=[('1', 'Kendisi'), ('2', 'Birinci Derece Yakını')], default='kendisi', max_length=25, null=True, verbose_name='Pep Degree'),
        ),
        migrations.AddField(
            model_name='partner',
            name='pep_description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pep Description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='sgk_job_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK Job Code'),
        ),
    ]
