# Generated by Django 5.1.4 on 2026-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0042_partner_pep_degree_partner_pep_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='salaried_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Salaried Title'),
        ),
    ]
