# Generated by Django 5.1.4 on 2026-04-08 07:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0043_partner_salaried_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Score')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_scores', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_scores', to='partners.partner')),
            ],
        ),
    ]
