# Generated by Django 5.1.4 on 2026-04-08 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0044_partnerscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('income_type', models.CharField(blank=True, choices=[('maas', 'Maaş'), ('ticari', 'Ticari Kazanç'), ('kira', 'Kira Geliri'), ('yatirim', 'Yatırım Geliri'), ('diger', 'Diğer')], default='maas', max_length=25, null=True, verbose_name='Income Type')),
                ('other_income', models.CharField(blank=True, max_length=140, null=True, verbose_name='Other Income')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_financial_profiles', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_financial_profiles', to='partners.partner')),
            ],
        ),
    ]
