# Generated by Django 5.1.4 on 2026-04-20 05:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0045_partnerfinancialprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfinancialprofile',
            name='income_type',
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='income_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('maas', 'Maaş'), ('ticari', 'Ticari Kazanç'), ('kira', 'Kira Geliri'), ('yatirim', 'Yatırım Geliri'), ('diger', 'Diğer')], max_length=25, verbose_name='Income Types'), blank=True, default=list, null=True, size=None),
        ),
    ]
