# Generated by Django 5.1.4 on 2026-04-21 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0046_remove_partnerfinancialprofile_income_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SgkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('sgk_job_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK Job ID')),
                ('sgk_job_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='SGK Job Code')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Description')),
                ('is_pep', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sgk_jobs', to='companies.company')),
            ],
        ),
    ]
