# Generated by Django 5.1.4 on 2026-04-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0047_sgkjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgkjob',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
    ]
