# Generated by Django 5.1.4 on 2026-04-21 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0048_alter_sgkjob_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='sgk_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sgk_job_partners', to='partners.sgkjob'),
        ),
    ]
