# Generated by Django 5.1.4 on 2026-05-11 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0049_partner_sgk_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfinancialprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='partner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='partner_financial_profile', serialize=False, to='partners.partner'),
        ),
    ]
