# Generated by Django 5.1.4 on 2026-05-12 09:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0050_remove_partnerfinancialprofile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='fund_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('satis', 'Satış Geliri'), ('maas', 'Maaş Birikimi'), ('kira', 'Kira Geliri'), ('miras', 'Miras'), ('sirket', 'Şirket Kazancı'), ('yurt_disi', 'Yurt Dışı Transfer'), ('diger', 'Diğer')], max_length=25, verbose_name='Fund Sources'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='other_fund_source',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Other Fund Source'),
        ),
    ]
