# Generated by Django 5.1.4 on 2026-05-12 12:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0051_partnerfinancialprofile_fund_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='sgk_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sgk_job_partner_financial_profiles', to='partners.sgkjob'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='fund_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('satis', 'Satış Geliri'), ('maas', 'Maaş Birikimi'), ('kira', 'Kira Geliri'), ('miras', 'Miras'), ('sirket', 'Şirket Kazancı'), ('yurtdisi', 'Yurt Dışı Transfer'), ('diger', 'Diğer')], max_length=25, verbose_name='Fund Sources'), blank=True, default=list, null=True, size=None),
        ),
    ]
