# Generated by Django 5.1.4 on 2026-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0052_partnerfinancialprofile_sgk_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='institution',
            field=models.CharField(blank=True, choices=[('ozel', 'Özel Sektör'), ('kamu', 'Kamu Kurumu'), ('serbest', 'Serbest Meslek'), ('emekli', 'Emekli'), ('ogrenci', 'Öğrenci'), ('ev', 'Ev Hanımı'), ('yok', 'Yok')], max_length=25, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('calisan', 'Çalışan'), ('yonetici', 'Yönetici'), ('ortak', 'Ortak'), ('yok', 'Yok')], max_length=25, null=True, verbose_name='Position'),
        ),
    ]
