# Generated by Django 5.1.4 on 2026-05-13 08:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0053_partnerfinancialprofile_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='bank_deposit_assets',
            field=models.CharField(blank=True, choices=[('0', '0-500.000'), ('1', '500.001-1.000.000'), ('2', '1.000.001-5.000.000'), ('3', '5.000.001-10.000.000'), ('4', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Bank Deposit Assets'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='investment_assets',
            field=models.CharField(blank=True, choices=[('0', '0-500.000'), ('1', '500.001-1.000.000'), ('2', '1.000.001-5.000.000'), ('3', '5.000.001-10.000.000'), ('4', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Investment Assets'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='other_assets',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Other Assets'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='real_estate_assets',
            field=models.CharField(blank=True, choices=[('0', '0-500.000'), ('1', '500.001-1.000.000'), ('2', '1.000.001-5.000.000'), ('3', '5.000.001-10.000.000'), ('4', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Real Estate Assets'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='vehicle_assets',
            field=models.CharField(blank=True, choices=[('0', '0-500.000'), ('1', '500.001-1.000.000'), ('2', '1.000.001-5.000.000'), ('3', '5.000.001-10.000.000'), ('4', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Vehicle Assets'),
        ),
    ]
