# Generated by Django 5.1.4 on 2026-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0055_alter_partnerfinancialprofile_bank_deposit_assets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='transaction_amount',
            field=models.CharField(blank=True, choices=[('0', '0 TL'), ('1', '1-100.000'), ('2', '100.001-500.000'), ('3', '500.001-2.000.000'), ('4', '2.000.001-10.000.000'), ('5', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Transaction Amount'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='bank_deposit_assets',
            field=models.CharField(blank=True, choices=[('0', '0 TL'), ('1', '1-100.000'), ('2', '100.001-500.000'), ('3', '500.001-2.000.000'), ('4', '2.000.001-10.000.000'), ('5', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Bank Deposit Assets'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='investment_assets',
            field=models.CharField(blank=True, choices=[('0', '0 TL'), ('1', '1-100.000'), ('2', '100.001-500.000'), ('3', '500.001-2.000.000'), ('4', '2.000.001-10.000.000'), ('5', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Investment Assets'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='other_assets',
            field=models.CharField(blank=True, choices=[('0', '0 TL'), ('1', '1-100.000'), ('2', '100.001-500.000'), ('3', '500.001-2.000.000'), ('4', '2.000.001-10.000.000'), ('5', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Other Assets'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='real_estate_assets',
            field=models.CharField(blank=True, choices=[('0', '0 TL'), ('1', '1-100.000'), ('2', '100.001-500.000'), ('3', '500.001-2.000.000'), ('4', '2.000.001-10.000.000'), ('5', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Real Estate Assets'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='vehicle_assets',
            field=models.CharField(blank=True, choices=[('0', '0 TL'), ('1', '1-100.000'), ('2', '100.001-500.000'), ('3', '500.001-2.000.000'), ('4', '2.000.001-10.000.000'), ('5', '10.000.001 ve üzeri')], max_length=25, null=True, verbose_name='Vehicle Assets'),
        ),
    ]
