# Generated by Django 5.1.4 on 2026-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0056_partnerfinancialprofile_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='transaction_frequency',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1-20'), ('2', '21-50'), ('3', '51-100'), ('4', '101-500'), ('5', '500 ve üzeri')], max_length=25, null=True, verbose_name='Transaction Frequency'),
        ),
    ]
