# Generated by Django 5.1.4 on 2026-05-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0057_partnerfinancialprofile_transaction_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='transaction_risk',
            field=models.CharField(blank=True, choices=[('riskli', 'Riskli'), ('riskli_degil', 'Riskli Değil')], max_length=25, null=True, verbose_name='Transaction Risk'),
        ),
    ]
