# Generated by Django 5.1.4 on 2026-05-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0058_partnerfinancialprofile_transaction_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='job_compliance',
            field=models.CharField(blank=True, choices=[('uyumlu', 'Uyumlu'), ('uyumlu_degil', 'Uyumlu Değil')], max_length=25, null=True, verbose_name='Job Compliance'),
        ),
    ]
