# Generated by Django 5.1.4 on 2026-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0059_partnerfinancialprofile_job_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('bireysel', 'Bireysel'), ('tuzel', 'Tüzel')], max_length=25, null=True, verbose_name='Customer Type'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_end_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_foreign_nationality',
            field=models.BooleanField(default=False),
        ),
    ]
