# Generated by Django 5.1.4 on 2026-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0061_partnerfinancialprofile_is_complex_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('as', 'A.Ş.'), ('ltd', 'LTD'), ('sahis', 'Şahıs Şirketi'), ('kollektif', 'Kollektif Şirket')], max_length=25, null=True, verbose_name='Company Type'),
        ),
    ]
