# Generated by Django 5.1.4 on 2026-05-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0062_partnerfinancialprofile_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_negative_news',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
    ]
