# Generated by Django 5.1.4 on 2026-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0063_partnerfinancialprofile_is_negative_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_balloon_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_cash_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='remitter_type',
            field=models.CharField(blank=True, choices=[('kendisi', 'Kendisi'), ('yakini', 'Yakını (Aile Bağı)'), ('ucuncu_kisi', '3. Kişi')], max_length=25, null=True, verbose_name='Remitter Type'),
        ),
    ]
