# Generated by Django 5.1.4 on 2026-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0064_partnerfinancialprofile_is_balloon_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
