# Generated by Django 5.1.4 on 2026-05-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0065_partnerfinancialprofile_is_blacklisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_administrative_follow_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_cheque_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_kkb_score_low',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_warning_notice',
            field=models.BooleanField(default=False),
        ),
    ]
