# Generated by Django 5.1.4 on 2026-05-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0066_partnerfinancialprofile_is_administrative_follow_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='real_estate_assets_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Real Estate Assets Count'),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='vehicle_assets_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Vehicle Assets Count'),
        ),
    ]
