# Generated by Django 5.2.14 on 2026-06-03 10:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0067_partnerfinancialprofile_real_estate_assets_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='fund_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('satis', 'Duran Varlık Satışı'), ('ticari', 'Ticari Kazanç'), ('maas', 'Maaş'), ('maas_birikimi', 'Maaş Birikimi'), ('kira', 'Kira Geliri'), ('miras', 'Miras'), ('sirket', 'Şirket Kazancı'), ('yurtdisi', 'Yurt Dışı Transfer'), ('belirsiz', 'Belirsiz Kaynak'), ('kripto', 'Kripto Kazancı'), ('diger', 'Diğer')], max_length=25, verbose_name='Fund Sources'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='income_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('maas', 'Maaş'), ('ticari', 'Ticari Kazanç'), ('kira', 'Kira Geliri'), ('yatirim', 'Yatırım Geliri'), ('belirsiz', 'Belirsiz Kaynak'), ('kripto', 'Kripto Kazancı'), ('diger', 'Diğer')], max_length=25, verbose_name='Income Types'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='institution',
            field=models.CharField(blank=True, choices=[('ozel', 'Özel Sektör'), ('kamu', 'Kamu Kurumu'), ('emekli', 'Emekli'), ('ogrenci', 'Öğrenci'), ('ev', 'Ev Hanımı'), ('issiz', 'İşsiz')], max_length=25, null=True, verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='position',
            field=models.CharField(blank=True, choices=[('calisan', 'Çalışan'), ('yonetici', 'Yönetici'), ('ortak', 'Ortak'), ('issiz', 'İşsiz'), ('firma_sahibi', 'Firma Sahibi')], max_length=25, null=True, verbose_name='Position'),
        ),
    ]
