# Generated by Django 5.2.14 on 2026-06-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0068_alter_partnerfinancialprofile_fund_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='other_assets_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Other Assets Count'),
        ),
    ]
