# Generated by Django 5.2.14 on 2026-06-03 14:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0069_partnerfinancialprofile_other_assets_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='other_assets_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Other Assets Amount'),
        ),
    ]
