# Generated by Django 5.2.14 on 2026-06-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0070_partnerfinancialprofile_other_assets_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='other_assets_description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Other Assets Description'),
        ),
    ]
