# Generated by Django 5.2.14 on 2026-06-04 08:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0071_partnerfinancialprofile_other_assets_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='fund_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('satis', 'Duran Varlık Satışı'), ('ticari', 'Ticari Kazanç'), ('maas', 'Maaş'), ('maas_birikimi', 'Maaş Birikimi'), ('kira', 'Kira Geliri'), ('miras', 'Miras'), ('sirket', 'Şirket Kazancı'), ('yurtdisi', 'Yurt Dışı Transfer'), ('belirsiz', 'Belirsiz Kaynak'), ('kripto', 'Kripto Kazancı'), ('yok', 'Kaynak Yok'), ('diger', 'Diğer')], max_length=25, verbose_name='Fund Sources'), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='income_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('maas', 'Maaş'), ('ticari', 'Ticari Kazanç'), ('kira', 'Kira Geliri'), ('yatirim', 'Yatırım Geliri'), ('belirsiz', 'Belirsiz Kaynak'), ('kripto', 'Kripto Kazancı'), ('yok', 'Gelir Yok'), ('diger', 'Diğer')], max_length=25, verbose_name='Income Types'), blank=True, default=list, null=True, size=None),
        ),
    ]
