# Generated by Django 5.2.14 on 2026-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0072_alter_partnerfinancialprofile_fund_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_offshore',
            field=models.BooleanField(default=False),
        ),
    ]
