# Generated by Django 5.2.14 on 2026-06-08 05:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0073_partnerfinancialprofile_is_offshore'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='income_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Income Amount'),
        ),
    ]
