# Generated by Django 5.2.14 on 2026-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0074_partnerfinancialprofile_income_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='balance_sheet_and_capital_structure',
            field=models.CharField(blank=True, choices=[('uygun', 'Uygun'), ('uygun_degil', 'Uygun Değil')], max_length=25, null=True, verbose_name='Balance Sheet and Capital Structure'),
        ),
    ]
