# Generated by Django 5.2.14 on 2026-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0075_partnerfinancialprofile_balance_sheet_and_capital_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_complex_structure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_high_risk_country',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_low_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_tax_haven',
            field=models.BooleanField(default=False),
        ),
    ]
