# Generated by Django 5.2.14 on 2026-06-08 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0076_partnerfinancialprofile_is_complex_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='bank_deposit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Bank Deposit Amount'),
        ),
    ]
