# Generated by Django 5.2.14 on 2026-06-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0077_partnerfinancialprofile_bank_deposit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('sanal_pos', 'Sanal POS'), ('kurum_odemesi', 'Kurum Ödemesi'), ('muhabir_banka', 'Muhabir Banka'), ('odeme_kurulusu', 'Ödeme Kuruluşu'), ('cek_senet', 'Çek/Senet')], max_length=25, null=True, verbose_name='Payment Type'),
        ),
    ]
