# Generated by Django 5.2.14 on 2026-06-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0078_partnerfinancialprofile_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerfinancialprofile',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_cek_senet_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_correspondent_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_institutional_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='is_payment_institution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerfinancialprofile',
            name='vpos_type',
            field=models.CharField(blank=True, choices=[('kendisi', 'Kendisi'), ('yakini', 'Yakını (Aile Bağı)'), ('ucuncu_kisi', '3. Kişi')], max_length=25, null=True, verbose_name='VPOS Type'),
        ),
    ]
