# Generated by Django 5.2.14 on 2026-06-08 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0079_remove_partnerfinancialprofile_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerInformationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('label', models.CharField(blank=True, max_length=250, null=True, verbose_name='Label')),
                ('file', models.FileField(blank=True, help_text='Please upload a file.', null=True, upload_to='docs/partners/partner/documents/', verbose_name='File')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_information_documents', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_information_documents', to='partners.partner')),
            ],
        ),
    ]
