# Generated by Django 5.2.14 on 2026-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0080_partnerinformationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='nace_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NACE Code'),
        ),
    ]
