# Generated by Django 5.2.14 on 2026-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0081_partner_nace_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='mother_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Mother Name'),
        ),
    ]
