# Generated by Django 5.2.14 on 2026-07-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0082_partner_mother_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='sex',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Sex'),
        ),
    ]
