# Generated by Django 5.2.14 on 2026-08-13 13:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0083_partner_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerscore',
            name='financial_profile_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Financial ProfileScore'),
        ),
    ]
