# Generated by Django 5.2.14 on 2026-08-17 08:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0084_partnerscore_financial_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerscore',
            name='cr_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='CR Score'),
        ),
        migrations.AddField(
            model_name='partnerscore',
            name='ilh_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='ILH Score'),
        ),
        migrations.AddField(
            model_name='partnerscore',
            name='mr_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='MR Score'),
        ),
        migrations.AddField(
            model_name='partnerscore',
            name='ok_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='OK Score'),
        ),
        migrations.AddField(
            model_name='partnerscore',
            name='uhr_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='UHR Score'),
        ),
    ]
