# Generated by Django 5.2.14 on 2026-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0085_partnerscore_cr_score_partnerscore_ilh_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerfinancialprofile',
            name='transaction_frequency',
            field=models.CharField(blank=True, choices=[('0_2', '0-2'), ('3_4', '3-4'), ('5_above', '5 ve üzeri')], max_length=25, null=True, verbose_name='Transaction Frequency'),
        ),
    ]
