# Generated by Django 5.1.4 on 2025-06-10 06:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankaTahsilati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('gonderen_unvani', models.CharField(max_length=250, verbose_name='Gönderen Ünvanı')),
                ('tc_vkn_no', models.CharField(max_length=140, verbose_name='TC/VKN NO')),
                ('aciklama', models.CharField(max_length=250, verbose_name='Açıklama')),
                ('tutar', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Tutar')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banka_tahsilatlari', to='companies.company')),
            ],
        ),
    ]
