# Generated by Django 5.1.4 on 2025-06-11 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0003_bankahareketleri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankaHareketleri',
        ),
    ]
