# Generated by Django 5.1.4 on 2025-06-11 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('converters', '0004_delete_bankahareketleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankaHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('gonderen_unvani', models.CharField(max_length=250, verbose_name='Gönderen Ünvanı')),
                ('musteri_unvani', models.CharField(max_length=250, verbose_name='Müşteri Ünvanı')),
                ('aciklama', models.CharField(max_length=250, verbose_name='Açıklama')),
                ('ucuncu_sahis_mi', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banka_hareketleri', to='companies.company')),
            ],
        ),
    ]
