# Generated by Django 5.1.4 on 2025-06-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converters', '0005_bankahareketi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankahareketi',
            name='ucuncu_sahis_mi_str',
            field=models.CharField(default='', max_length=25, verbose_name='Üçüncü Şahıs'),
        ),
    ]
