# Generated by Django 5.1.4 on 2025-07-01 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Account ID')),
                ('crm_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM ID')),
                ('crm_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='CRM Type')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Name')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_accounts', to='companies.company')),
            ],
        ),
    ]
