# Generated by Django 5.1.4 on 2025-07-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0028_partner_crm_code'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeaccount',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_trade_accounts', to='partners.partner'),
        ),
    ]
