# Generated by Django 5.1.4 on 2025-10-13 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_exportprocess_export_url'),
        ('companies', '0005_usercompany_display_currency'),
        ('leasing', '0047_lease_is_under_review'),
        ('partners', '0036_partner_is_commercial'),
        ('trade', '0002_tradeaccount_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('trade_transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trade Transaction ID')),
                ('posting_group_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Posting Group ID')),
                ('posting_group_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Posting Group Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('document_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Document No')),
                ('amount_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount Type')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due Date')),
                ('record_date', models.DateTimeField(blank=True, null=True, verbose_name='Record Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('local_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Local Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Exchange Rate')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_transactions', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_trade_transactions', to='common.currency')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_trade_transactions', to='leasing.lease')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_trade_transactions', to='partners.partner')),
            ],
        ),
    ]
