# Generated by Django 5.1.4 on 2025-10-14 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_tradetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetransaction',
            name='description',
            field=models.CharField(blank=True, max_length=750, null=True, verbose_name='Description'),
        ),
    ]
