# Generated by Django 5.1.4 on 2025-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_alter_tradetransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradetransaction',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
