# Generated by Django 5.1.4 on 2026-01-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_tradetransaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='delete_status',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Delete Status'),
        ),
    ]
