# Generated by Django 5.2.14 on 2026-07-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_tradetransaction_delete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='posting_type_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Posting Type ID'),
        ),
        migrations.AddField(
            model_name='tradetransaction',
            name='posting_type_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Posting Type Name'),
        ),
    ]
