# Generated by Django 5.1.4 on 2025-08-28 07:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('leasing', '0042_bankactivity_is_reliable_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountDebitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('process_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Process Group')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('process_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Process Type')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Debit Amount')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Credit Amount')),
                ('real_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Real Amount')),
                ('for_default_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='For Default Amount')),
                ('adat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='adat Amount')),
                ('default_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Default Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interest Rate')),
                ('overdue_interest_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Interest Rate')),
                ('day', models.IntegerField(default=0, verbose_name='Day')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_debits', to='companies.company')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_amount_debits', to='leasing.lease')),
            ],
        ),
    ]
