# Generated by Django 5.1.4 on 2025-08-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountdebittransaction',
            name='trn_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Trn Id'),
        ),
    ]
