# Generated by Django 5.1.4 on 2025-08-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_amountdebittransaction_trn_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountdebittransaction',
            name='process_group_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Process Group ID'),
        ),
    ]
