# Generated by Django 5.1.4 on 2025-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_amountdebittransaction_process_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountdebittransaction',
            name='overdue_interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Interest Rate'),
        ),
    ]
