def bl222af_row_names():
    return  [
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'AKTİF KALEMLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'I. NAKİT, NAKİT BENZERLERİ ve MERKEZ BANKASI', 'font_weight': 'bold'},
                    'tps': ['010.00.1.00','022'],
                    'yps': ['023'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'II. GERÇEĞE UYGUN DEĞER FARKI KÂR/ZARARA YANSITILAN FİNANSAL VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['030.02.0.00','030.19.0.00','038.00.0.00'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'III. TÜREV FİNANSAL VARLIKLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'IV. GERÇEĞE UYGUN DEĞER FARKI DİĞER KAPSAMLI GELİRE YANSITILAN FİNANSAL VARLIKLAR (Net)  ', 'font_weight': 'bold'},
                    'tps': ['032.02.0.00','038.01.0.00','032.90.0.0001','032.90.0.0002','032.90.0.0003'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'V. İTFA EDİLMİŞ MALİYETİ İLE ÖLÇÜLEN FİNANSAL VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4','222.99.2','222.01.3','170','176','180'],
                    'yps': ['151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4','223.98','223.99.1','223.99.2','223.01.3','171','177','181'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.1 Faktoring Alacakları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.1.1 İskontolu Faktoring Alacakları (Net)', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.1.2 Diğer Faktoring Alacakları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.2 Tasarruf Finansman Alacakları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.2.1 Tasarruf Fon Havuzundan ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.2.2 Özkaynaklardan', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3 Finansman Kredileri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3.1 Tüketici Kredileri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3.2 Kredi Kartları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3.3 Taksitli Ticari Krediler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4 Kiralama İşlemleri (Net)', 'font_weight': 'normal'},
                    'tps': ['150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4'],
                    'yps': ['151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4.1 Finansal Kiralama Alacakları', 'font_weight': 'normal'},
                    'tps': ['150.00','154.02.1','154.02.2','154.02.3'],
                    'yps': ['151.00','151.02.1','155.02.1','155.02.2','155.02.3'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4.2 Faaliyet Kiralaması Alacakları', 'font_weight': 'normal'},
                    'tps': ['150.02'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4.3 Kazanılmamış Gelirler (-)', 'font_weight': 'normal'},
                    'tps': ['150.01','154.03.4'],
                    'yps': ['151.01','151.98','155.03.4'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.5 İtfa Edilmiş Maliyeti İle Ölçülen Diğer Finansal Varlıklar', 'font_weight': 'normal'},
                    'tps': ['222.99.2','222.01.3'],
                    'yps': ['223.98','223.99.1','223.99.2','223.01.3'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.6 Takipteki Alacaklar', 'font_weight': 'normal'},
                    'tps': ['170','176'],
                    'yps': ['171','177'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.7 Beklenen Zarar Karşılıkları/Özel Karşılıklar (-)', 'font_weight': 'normal'},
                    'tps': ['180'],
                    'yps': ['181'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VI. ORTAKLIK YATIRIMLARI', 'font_weight': 'bold'},
                    'tps': ['246'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '6.1 İştirakler (Net)', 'font_weight': 'normal'},
                    'tps': ['246'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '6.2 Bağlı Ortaklıklar (Net)', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '6.3 Birlikte Kontrol Edilen Ortaklıklar (İş Ortaklıkları) (Net)  ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VII. MADDİ DURAN VARLIKLAR (Net) ', 'font_weight': 'bold'},
                    'tps': ['250','252','254','256.00','256.01','256.02','256.08'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VIII. MADDİ OLMAYAN DURAN VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['258','256.07'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'IX. YATIRIM AMAÇLI GAYRİMENKULLER (Net)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'X. CARİ DÖNEM VERGİ VARLIĞI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'XI. ERTELENMİŞ VERGİ VARLIĞ', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'XII. DİĞER AKTİFLER', 'font_weight': 'bold'},
                    'tps': ['226','228','278','280.01','260.01','260.04','280.00','260.00','260.03','280.99'],
                    'yps': ['227','229','279','281.98','281.00','281.99'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'ARA TOPLAM', 'font_weight': 'bold'},
                    'tps': ['010.00.1.00','022','030.02.0.00','030.19.0.00','038.00.0.00','032.02.0.00','038.01.0.00','032.90.0.0001','032.90.0.0002','032.90.0.0003','150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4','222.99.2','222.01.3','170','176','180','246','250','252','254','256.00','256.01','256.02','256.08','258','256.07','226','228','278','280.01','260.01','260.04','280.00','260.00','260.03','280.99'],
                    'yps': ['023','151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4','223.98','223.99.1','223.99.2','223.01.3','171','177','181','227','229','279','281.98','281.00','281.99'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'XIII. SATIŞ AMAÇLI ELDE TUTULAN VE DURDURULAN FAALİYETLERE İLİŞKİN VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['238'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '13.1 Satış Amaçlı ', 'font_weight': 'normal'},
                    'tps': ['238'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '13.2 Durdurulan Faaliyetlere İlişkin', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VARLIK TOPLAMI', 'font_weight': 'bold'},
                    'tps': ['010.00.1.00','022','030.02.0.00','030.19.0.00','038.00.0.00','032.02.0.00','038.01.0.00','032.90.0.0001','032.90.0.0002','032.90.0.0003','150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4','222.99.2','222.01.3','170','176','180','246','250','252','254','256.00','256.01','256.02','256.08','258','256.07','226','228','278','280.01','260.01','260.04','280.00','260.00','260.03','280.99','238'],
                    'yps': ['023','151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4','223.98','223.99.1','223.99.2','223.01.3','171','177','181','227','229','279','281.98','281.00','281.99'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'PASİF KALEMLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'I. ALINAN KREDİLER', 'font_weight': 'bold'},
                    'tps': ['342','360.00.1','361.00.1'],
                    'yps': ['343'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'II. FAKTORİNG BORÇLARI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'III. TASARRUF FON HAVUZUNDAN BORÇLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'IV. KİRALAMA İŞLEMLERİNDEN BORÇLAR', 'font_weight': 'bold'},
                    'tps': ['352.00'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'V. İHRAÇ EDİLEN MENKUL KIYMETLER (Net)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VI. GERÇEĞE UYGUN DEĞER FARKI KAR ZARARA YANSITILAN FİNANSAL YÜKÜMLÜLÜKLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VII. TÜREV FİNANSAL YÜKÜMLÜLÜKLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VIII. KARŞILIKLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.1 Yeniden Yapılanma Karşılığı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.2 Çalışan Hakları Yükümlülüğü Karşılığı', 'font_weight': 'normal'},
                    'tps': ['350.01','350.03'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.3 Genel Karşılıklar', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.4 Diğer Karşılıklar', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'IX. CARİ VERGİ BORCU', 'font_weight': 'bold'},
                    'tps': ['350.04'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'X. ERTELENMİŞ VERGİ BORCU', 'font_weight': 'bold'},
                    'tps': ['262','386'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'XI. SERMAYE BENZERİ BORÇLANMA ARAÇLARI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'XII. DİĞER YÜKÜMLÜLÜKLER', 'font_weight': 'bold'},
                    'tps': ['360.09.1','390','392','380'],
                    'yps': ['361.09.1','361.99','391','393'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'ARA TOPLAM', 'font_weight': 'bold'},
                    'tps': ['342','360.00.1','361.00.1','352.00','350.04','262','386','360.09.1','390','392','380'],
                    'yps': ['343','361.09.1','361.99','391','393'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'XIII. SATIŞ AMAÇLI ELDE TUTULAN VE DURDURULAN FAALİYETLERE İLİŞKİN DURAN VARLIK BORÇLARI (Net)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '13.1 Satış Amaçlı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '13.2 Durdurulan Faaliyetlere İlişkin', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'XIV. ÖZKAYNAKLAR', 'font_weight': 'bold'},
                    'tps': ['410','412','414.03.1','414.05.0','414.09.0','420.00','448','420.09.2','440','442','5','6','7','8'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.1 Ödenmiş Sermaye', 'font_weight': 'normal'},
                    'tps': ['410','412'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.2 Sermaye Yedekleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.2.1 Hisse Senedi İhraç Primleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.2.2 Hisse Senedi İptal Kârları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.2.3 Diğer Sermaye Yedekleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.3 Kâr veya Zararda Yeniden Sınıflandırılmayacak Birikmiş Diğer Kapsamlı Gelirler veya Giderler', 'font_weight': 'normal'},
                    'tps': ['414.03.1','414.05.0','414.09.0'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.4 Kâr veya Zararda Yeniden Sınıflandırılacak Birikmiş Diğer Kapsamlı Gelirler veya Giderler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.5 Kâr Yedekleri', 'font_weight': 'normal'},
                    'tps': ['420.00','448','420.09.2'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.5.1 Yasal Yedekler', 'font_weight': 'normal'},
                    'tps': ['420.00','448'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.5.2 Statü Yedekleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.5.3 Olağanüstü Yedekler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.5.4 Diğer Kâr Yedekleri', 'font_weight': 'normal'},
                    'tps': ['420.09.2'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.6 Kâr veya Zarar', 'font_weight': 'normal'},
                    'tps': ['440','442','5','6','7','8'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.6.1 Geçmiş Yıllar Kâr veya Zararı', 'font_weight': 'normal'},
                    'tps': ['440','442'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '14.6.2 Dönem Net Kâr veya Zararı', 'font_weight': 'normal'},
                    'tps': ['5','6','7','8'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'YÜKÜMLÜLÜK TOPLAMI', 'font_weight': 'bold'},
                    'tps': ['342','360.00.1','361.00.1','352.00','350.04','262','386','360.09.1','390','392','380','410','412','414.03.1','414.05.0','414.09.0','420.00','448','420.09.2','440','442','5','6','7','8'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'NAZIM HESAP KALEMLERİ', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'I. RİSKİ ÜSTLENİLEN FAKTORİNG İŞLEMLERİ', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'II. RİSKİ ÜSTLENİLMEYEN FAKTORİNG İŞLEMLERİ', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'III. TASARRUF FİNANSMAN SÖZLEŞMELERİ İŞLEMLERİ', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'IV. ALINAN TEMİNATLAR', 'font_weight': 'bold'},
                    'tps': ['924'],
                    'yps': ['925'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'V. VERİLEN TEMİNATLAR', 'font_weight': 'bold'},
                    'tps': ['934'],
                    'yps': ['935'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VI. TAAHHÜTLER', 'font_weight': 'bold'},
                    'tps': ['978'],
                    'yps': ['979'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '6.1 Cayılamaz Taahhütler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '6.2 Cayılabilir Taahhütler', 'font_weight': 'normal'},
                    'tps': ['978'],
                    'yps': ['979'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '6.2.1 Kiralama Taahhütleri', 'font_weight': 'normal'},
                    'tps': ['978'],
                    'yps': ['979'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '6.2.1.1 Finansal Kiralama Taahhütleri', 'font_weight': 'normal'},
                    'tps': ['978'],
                    'yps': ['979'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '6.2.1.2 Faaliyet Kiralama Taahhütleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '6.2.2 Diğer Cayılabilir Taahhütler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VII. TÜREV FİNANSAL ARAÇLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.1 Riskten Korunma Amaçlı Türev Finansal Araçlar', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.1.1 Gerçeğe Uygun Değer Riskinden Korunma Amaçlı İşlemler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.1.2 Nakit Akış Riskinden Korunma Amaçlı İşlemler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.1.3 Yurtdışındaki Net Yatırım Riskinden Korunma Amaçlı İşlemler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.2 Alım Satım Amaçlı İşlemler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.2.1 Vadeli  Alım-Satım İşlemleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.2.2 Swap Alım Satım İşlemleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.2.3 Alım Satım Opsiyon İşlemleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.2.4 Futures Alım Satım İşlemleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '7.2.5 Diğer', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VIII. EMANET KIYMETLER', 'font_weight': 'bold'},
                    'tps': ['982'],
                    'yps': ['983'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'NAZIM HESAPLAR TOPLAMI', 'font_weight': 'bold'},
                    'tps': ['924','934','978','982'],
                    'yps': ['925','935','979','983'],
                },
            ]

def kz222af_row_names():
    return  [
                {
                    'type': '',
                    'title': {'text': 'I. ESAS FAALİYET GELİRLERİ', 'font_weight': 'bold'},
                    'tps': ['548','582','704'],
                    'yps': ['549','583','705'],
                },
                # arada boş satırlar var
                {
                    'type': '',
                    'title': {'text': 'KİRALAMA GELİRLERİ', 'font_weight': 'bold'},
                    'tps': ['548','582','704'],
                    'yps': ['549','583','705'],
                },
                {
                    'type': '',
                    'title': {'text': '1.5 Finansal Kiralama Gelirleri', 'font_weight': 'normal'},
                    'tps': ['548','582'],
                    'yps': ['549','583'],
                },
                {
                    'type': '',
                    'title': {'text': '1.6 Faaliyet Kiralaması Gelirleri', 'font_weight': 'normal'},
                    'tps': ['704'],
                    'yps': ['705'],
                },
                # arada boş satırlar var
                {
                    'type': '',
                    'title': {'text': 'II. FİNANSMAN GİDERLERİ (-)', 'font_weight': 'bold'},
                    'tps': ['622.00','622.09','644.00','698.99.00','840'],
                    'yps': ['623.00','623.09'],
                },
                # arada boş satırlar var
                {
                    'type': '',
                    'title': {'text': '2.2 Kullanılan Kredilere Verilen Faizler', 'font_weight': 'normal'},
                    'tps': ['622.00','622.09'],
                    'yps': ['623.00','623.09'],
                },
                # arada boş satırlar var
                {
                    'type': '',
                    'title': {'text': '2.4 Kiralama İşlemlerine İlişkin Faiz Giderleri', 'font_weight': 'normal'},
                    'tps': ['644.00'],
                    'yps': [],
                },
                # arada boş satırlar var
                {
                    'type': '',
                    'title': {'text': '2.6 Diğer Faiz Giderleri', 'font_weight': 'normal'},
                    'tps': ['698.99.00'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '2.7 Verilen Ücret ve Komisyonlar', 'font_weight': 'normal'},
                    'tps': ['840'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'III. BRÜT K/Z (I+II)', 'font_weight': 'bold'},
                    'tps': ['548','582','704','840'],
                    'yps': ['549','583','705'],
                },
                {
                    'type': '',
                    'title': {'text': 'IV. ESAS FAALİYET GİDERLERİ (-)', 'font_weight': 'bold'},
                    'tps': ['810','820.01','820.03.9.00','882'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '4.1 Personel Giderleri', 'font_weight': 'normal'},
                    'tps': ['810','820.01','820.03.9.00'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '4.2 Kıdem Tazminatı Karşılığı Gideri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                # arada boş satırlar var
                {
                    'type': '',
                    'title': {'text': '4.4 Genel İşletme Giderleri', 'font_weight': 'normal'},
                    'tps': ['830','850','880'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '4.5 Diğer', 'font_weight': 'normal'},
                    'tps': ['882'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'V. BRÜT FAALİYET K/Z (III+IV)', 'font_weight': 'bold'},
                    'tps': ['548','582','704','840','810','820.01','820.03.9.00','882'],
                    'yps': ['549','583','705'],
                },
                {
                    'type': '',
                    'title': {'text': 'VI. DİĞER FAALİYET GELİRLERİ', 'font_weight': 'bold'},
                    'tps': ['570','780.09.001','790','792'],
                    'yps': ['571','861','599','791'],
                },
                {
                    'type': '',
                    'title': {'text': '6.1 Bankalardan Alınan Faizler', 'font_weight': 'normal'},
                    'tps': ['570'],
                    'yps': ['571'],
                },
                {
                    'type': '',
                    'title': {'text': '6.2 Menkul Değerlerden Alınan Faizler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '6.3 Temettü Gelirleri', 'font_weight': 'normal'},
                    'tps': ['780.09.001'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '6.4 Sermaye Piyasası İşlemleri Kârı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '6.5 Türev Finansal İşlemler Kârı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '6.6 Kambiyo İşlemleri Kârı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': ['861'],
                },
                {
                    'type': '',
                    'title': {'text': '6.7 Diğer', 'font_weight': 'normal'},
                    'tps': ['790','792'],
                    'yps': ['599','791'],
                },
                {
                    'type': '',
                    'title': {'text': 'VII. KARŞILIK GİDERLERİ', 'font_weight': 'bold'},
                    'tps': ['820.00'],
                    'yps': ['821.00'],
                },
                {
                    'type': '',
                    'title': {'text': '7.1 Özel Karşılıklar ', 'font_weight': 'normal'},
                    'tps': ['820.00'],
                    'yps': ['821.00'],
                },
                {
                    'type': '',
                    'title': {'text': '7.2 Beklenen Zarar Karşılıkları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '7.3 Genel Karşılıklar', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '7.4 Diğer', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'VIII. DİĞER FAALİYET GİDERLERİ (-)', 'font_weight': 'bold'},
                    'tps': ['820.03.1'],
                    'yps': ['861'],
                },
                {
                    'type': '',
                    'title': {'text': '8.1 Menkul Değerler Değer Düşüş Gideri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '8.2 Duran Varlıklar Değer Düşüş Giderleri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '8.3 Sermaye Piyasası İşlemleri Zararı ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '8.4 Türev Finansal İşlemlerden Zarar ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '8.5 Kambiyo İşlemleri Zararı ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': ['861'],
                },
                {
                    'type': '',
                    'title': {'text': '8.6 Diğer ', 'font_weight': 'normal'},
                    'tps': ['820.03.1'],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'IX. NET FAALİYET K/Z (V+…+VIII)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'X. BİRLEŞME İŞLEMİ SONRASINDA GELİR OLARAK KAYDEDİLEN FAZLALIK TUTARI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XI. ÖZKAYNAK YÖNTEMİ UYGULANAN ORTAKLIKLARDAN KÂR/ZARAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XII. NET PARASAL POZİSYON KÂRI/ZARARI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XIII. SÜRDÜRÜLEN FAALİYETLER VERGİ ÖNCESİ K/Z (IX+X+XI+XII)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XIV. SÜRDÜRÜLEN FAALİYETLER VERGİ KARŞILIĞI (±)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '14.1 Cari Vergi Karşılığı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '14.2 Ertelenmiş Vergi Gider Etkisi (+)', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': '14.3 Ertelenmiş Vergi Gelir Etkisi (-)', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XV. SÜRDÜRÜLEN FAALİYETLER DÖNEM NET K/Z (XIII±XIV)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XX. DURDURULAN FAALİYETLER DÖNEM NET K/Z (XVIII±XIX)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': '',
                    'title': {'text': 'XXI. DÖNEM NET KARI/ZARARI (XV+XX)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
    ]