def bl222af_row_names():
    return  [
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'AKTİF KALEMLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'I. NAKİT, NAKİT BENZERLERİ ve MERKEZ BANKASI', 'font_weight': 'bold'},
                    'tps': ['010.00.1.00','022'],
                    'yps': ['023'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'II. GERÇEĞE UYGUN DEĞER FARKI KÂR/ZARARA YANSITILAN FİNANSAL VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['030.02.0.00','030.19.0.00','038.00.0.00'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'III. TÜREV FİNANSAL VARLIKLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'IV. GERÇEĞE UYGUN DEĞER FARKI DİĞER KAPSAMLI GELİRE YANSITILAN FİNANSAL VARLIKLAR (Net)  ', 'font_weight': 'bold'},
                    'tps': ['032.02.0.00','038.01.0.00','032.90.0.0001','032.90.0.0002','032.90.0.0003'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'V. İTFA EDİLMİŞ MALİYETİ İLE ÖLÇÜLEN FİNANSAL VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4','222.99.2','222.01.3','170','176','180'],
                    'yps': ['151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4','223.98','223.99.1','223.99.2','223.01.3','171','177','181'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.1 Faktoring Alacakları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.1.1 İskontolu Faktoring Alacakları (Net)', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.1.2 Diğer Faktoring Alacakları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.2 Tasarruf Finansman Alacakları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.2.1 Tasarruf Fon Havuzundan ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.2.2 Özkaynaklardan', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3 Finansman Kredileri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3.1 Tüketici Kredileri', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3.2 Kredi Kartları', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.3.3 Taksitli Ticari Krediler', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4 Kiralama İşlemleri (Net)', 'font_weight': 'normal'},
                    'tps': ['150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4'],
                    'yps': ['151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4.1 Finansal Kiralama Alacakları', 'font_weight': 'normal'},
                    'tps': ['150.00','154.02.1','154.02.2','154.02.3'],
                    'yps': ['151.00','151.02.1','155.02.1','155.02.2','155.02.3'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4.2 Faaliyet Kiralaması Alacakları', 'font_weight': 'normal'},
                    'tps': ['150.02'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.4.3 Kazanılmamış Gelirler (-)', 'font_weight': 'normal'},
                    'tps': ['150.01','154.03.4'],
                    'yps': ['151.01','151.98','155.03.4'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.5 İtfa Edilmiş Maliyeti İle Ölçülen Diğer Finansal Varlıklar', 'font_weight': 'normal'},
                    'tps': ['222.99.2','222.01.3'],
                    'yps': ['223.98','223.99.1','223.99.2','223.01.3'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.6 Takipteki Alacaklar', 'font_weight': 'normal'},
                    'tps': ['170','176'],
                    'yps': ['171','177'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '5.7 Beklenen Zarar Karşılıkları/Özel Karşılıklar (-)', 'font_weight': 'normal'},
                    'tps': ['180'],
                    'yps': ['181'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VI. ORTAKLIK YATIRIMLARI', 'font_weight': 'bold'},
                    'tps': ['246'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '6.1 İştirakler (Net)', 'font_weight': 'normal'},
                    'tps': ['246'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '6.2 Bağlı Ortaklıklar (Net)', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '6.3 Birlikte Kontrol Edilen Ortaklıklar (İş Ortaklıkları) (Net)  ', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VII. MADDİ DURAN VARLIKLAR (Net) ', 'font_weight': 'bold'},
                    'tps': ['250','252','254','256.00','256.01','256.02','256.08'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VIII. MADDİ OLMAYAN DURAN VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['258','256.07'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'IX. YATIRIM AMAÇLI GAYRİMENKULLER (Net)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'X. CARİ DÖNEM VERGİ VARLIĞI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'XI. ERTELENMİŞ VERGİ VARLIĞ', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'XII. DİĞER AKTİFLER', 'font_weight': 'bold'},
                    'tps': ['226','228','278','280.01','260.01','260.04','280.00','260.00','260.03','280.99'],
                    'yps': ['227','229','279','281.98','281.00','281.99'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'ARA TOPLAM', 'font_weight': 'bold'},
                    'tps': ['010.00.1.00','022','030.02.0.00','030.19.0.00','038.00.0.00','032.02.0.00','038.01.0.00','032.90.0.0001','032.90.0.0002','032.90.0.0003','150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4','222.99.2','222.01.3','170','176','180','246','250','252','254','256.00','256.01','256.02','256.08','258','256.07','226','228','278','280.01','260.01','260.04','280.00','260.00','260.03','280.99'],
                    'yps': ['023','151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4','223.98','223.99.1','223.99.2','223.01.3','171','177','181','227','229','279','281.98','281.00','281.99'],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'XIII. SATIŞ AMAÇLI ELDE TUTULAN VE DURDURULAN FAALİYETLERE İLİŞKİN VARLIKLAR (Net)', 'font_weight': 'bold'},
                    'tps': ['238'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '13.1 Satış Amaçlı ', 'font_weight': 'normal'},
                    'tps': ['238'],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': '13.2 Durdurulan Faaliyetlere İlişkin', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'AKTİF KALEMLER',
                    'title': {'text': 'VARLIK TOPLAMI', 'font_weight': 'bold'},
                    'tps': ['010.00.1.00','022','030.02.0.00','030.19.0.00','038.00.0.00','032.02.0.00','038.01.0.00','032.90.0.0001','032.90.0.0002','032.90.0.0003','150.00','154.02.1','154.02.2','154.02.3','150.02','150.01','154.03.4','222.99.2','222.01.3','170','176','180','246','250','252','254','256.00','256.01','256.02','256.08','258','256.07','226','228','278','280.01','260.01','260.04','280.00','260.00','260.03','280.99','238'],
                    'yps': ['023','151.00','151.02.1','155.02.1','155.02.2','155.02.3','151.01','151.98','155.03.4','223.98','223.99.1','223.99.2','223.01.3','171','177','181','227','229','279','281.98','281.00','281.99'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'PASİF KALEMLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'I. ALINAN KREDİLER', 'font_weight': 'bold'},
                    'tps': ['342','360.00.1','361.00.1'],
                    'yps': ['343'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'II. FAKTORİNG BORÇLARI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'III. TASARRUF FON HAVUZUNDAN BORÇLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'IV. KİRALAMA İŞLEMLERİNDEN BORÇLAR', 'font_weight': 'bold'},
                    'tps': ['352.00'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'V. İHRAÇ EDİLEN MENKUL KIYMETLER (Net)', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VI. GERÇEĞE UYGUN DEĞER FARKI KAR ZARARA YANSITILAN FİNANSAL YÜKÜMLÜLÜKLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VII. TÜREV FİNANSAL YÜKÜMLÜLÜKLER', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'VIII. KARŞILIKLAR', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.1 Yeniden Yapılanma Karşılığı', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.2 Çalışan Hakları Yükümlülüğü Karşılığı', 'font_weight': 'normal'},
                    'tps': ['350.01','350.03'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.3 Genel Karşılıklar', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': '8.4 Diğer Karşılıklar', 'font_weight': 'normal'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'IX. CARİ VERGİ BORCU', 'font_weight': 'bold'},
                    'tps': ['350.04'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'X. ERTELENMİŞ VERGİ BORCU', 'font_weight': 'bold'},
                    'tps': ['262','386'],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'XI. SERMAYE BENZERİ BORÇLANMA ARAÇLARI', 'font_weight': 'bold'},
                    'tps': [],
                    'yps': [],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'XII. DİĞER YÜKÜMLÜLÜKLER', 'font_weight': 'bold'},
                    'tps': ['360.09.1','390','392','380'],
                    'yps': ['361.09.1','361.99','391','393'],
                },
                {
                    'type': 'PASİF KALEMLER',
                    'title': {'text': 'ARA TOPLAM', 'font_weight': 'bold'},
                    'tps': ['342','360.00.1','361.00.1','352.00','350.04','262','386','360.09.1','390','392','380'],
                    'yps': ['343','361.09.1','361.99','391','393'],
                },
            ]