SELECT
    MIN(f.FREE_PART_ID) AS FREE_PART_ID,
    f.FREE_PART_NO,
    f.PROJECT_ID,
    f.PARCEL_NO,
    b.BLOCK_NO
FROM
    RPR_FREE_PART_LIST_FOR_DET f
LEFT JOIN
    RPR_BLOCK_DEFINITION_LIST b ON f.BLOCK_ID = b.BLOCK_ID
GROUP BY
    f.FREE_PART_NO,
    f.PROJECT_ID,
    f.PARCEL_NO,
    b.BLOCK_NO
