SELECT
    f.FREE_PART_ID,
    f.FREE_PART_NO,
    f.PROJECT_ID,
    f.PARCEL_NO,
    b.BLOCK_NO,
    f.BBSN_NO
FROM
    RPR_PROJECT_FREE_PART f
    LEFT JOIN RPR_PROJECT_BLOCK_LIST b ON f.BLOCK_ID = b.BLOCK_ID

