# Generated by Django 5.1.4 on 2025-09-16 14:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0013_exportprocess_export_url'),
        ('companies', '0005_usercompany_display_currency'),
        ('leasing', '0043_bankactivity_finmaks_transaction'),
        ('partners', '0035_partner_is_reliable_person_partner_is_scan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAdvanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('bank', models.CharField(blank=True, max_length=140, null=True, verbose_name='Bank')),
                ('bank_code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Bank Code')),
                ('bank_branch_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Branch Code')),
                ('bank_account_no', models.CharField(blank=True, max_length=25, null=True, verbose_name='Bank Account No')),
                ('cross_bank_code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Cross Bank Code')),
                ('cross_bank_branch_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Cross Bank Branch Code')),
                ('cross_bank_account_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Cross Bank Account No')),
                ('process_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Process Code')),
                ('credit_or_debit', models.CharField(blank=True, max_length=25, null=True, verbose_name='Credit Or Debit')),
                ('kontrat_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Kontrat No')),
                ('process_date', models.DateTimeField(blank=True, null=True, verbose_name='Process Date')),
                ('process_date_date', models.DateField(blank=True, null=True, verbose_name='Process Date Date')),
                ('process_type', models.CharField(blank=True, choices=[('in', 'In'), ('out', 'Out')], default='in', max_length=25, null=True, verbose_name='Process Type')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('receipt_no', models.CharField(blank=True, max_length=140, null=True, verbose_name='Receipt No')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('tc_vkn_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='TC/VKN No')),
                ('is_processed', models.BooleanField(default=False)),
                ('is_third_person', models.BooleanField(default=False)),
                ('is_reliable_person', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_advance_activities', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_partner_advance_activities', to='common.currency')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_partner_advance_activities', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAdvanceActivityLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('processed_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Processed Amount')),
                ('leaseflex_automation', models.BooleanField(default=False)),
                ('is_third_person', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_advance_activity_leases', to='companies.company')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_advance_activity_leases', to='leasing.lease')),
                ('partner_advance_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_advance_activity_partner_advance_activity_leases', to='operation.partneradvanceactivity')),
            ],
        ),
    ]
