"""
Django settings for marswide_backend project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from decouple import config, Csv
from celery.schedules import crontab

import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
import ollama
import sentry_sdk

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = str(os.getenv('SECRET_KEY'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast = bool, default = False)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast = Csv(), default = "*,www.marswide.com,marswide.com")


# Application definition

INSTALLED_APPS = [
    "daphne",
    "clearcache",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    "channels",
    "rest_framework",
    "rest_framework_datatables_editor",
    "drf_multiple_model",
    "django_filters",
    "django_cleanup.apps.CleanupConfig",
    "corsheaders",
    "simple_history",
    "django_ckeditor_5",
    "django_celery_results",
    "django_celery_beat",
    "django_select2",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_extensions",
    "auditlog",
    "users",
    "common",
    "subscriptions",
    "companies",
    "mikro",
    "partners",
    "notifications",
    "data",
    "geoip2",
    "accounting",
    "products",
    "converters",
    "contracts",
    "leasing",
    "quotations",
    "ledger",
    "trade",
    "projects",
    "purchasing",
    "risk",
    "finance",
    "underwriting",
    "compliance",
    "operation",
    "communication",
    "inventory",
    "agent",
    "krs",
    "ai"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'common.middleware.ThreadLocalMiddleware',
    'core.middleware.CurrentUserMiddleware',
    'core.middleware.CurrentRequestMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'
CHANNEL_LAYERS= {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
            "capacity": 5000,
            "group_expiry": 60 * 5
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DB_TEST = config('DB_TEST', cast = bool, default = False)

# if DB_TEST:
#     DATABASES = {
#             'default': {
#                 'ENGINE': 'dj_db_conn_pool.backends.postgresql',
#                 'NAME': 'postgres',
#                 'USER': 'postgres',
#                 'PASSWORD': 'postgres',
#                 'HOST': 'db',
#                 'PORT': '',
#                 'POOL_OPTIONS': {
#                     'POOL_SIZE': 100,
#                     'MAX_OVERFLOW': 50,
#                     'RECYCLE': 300
#                 },
#                 #'CONN_MAX_AGE': 30, # Bağlantı ömrü (saniye cinsinden)
#                 "TEST": {
#                     "NAME": "marswidedb_test",
#                 },
#             }
#     }
# else:
#     DATABASES = {
#             'default': {
#                 'ENGINE': 'dj_db_conn_pool.backends.postgresql',
#                 'NAME': str(os.getenv('PG_DB')),
#                 'USER': str(os.getenv('PG_USER')),
#                 'PASSWORD': str(os.getenv('PG_PASSWORD')),
#                 'HOST': 'db',
#                 'PORT': '',
#                 'POOL_OPTIONS': {
#                     'POOL_SIZE': 100,
#                     'MAX_OVERFLOW': 50,
#                     'RECYCLE': 300
#                 },
#                 #'CONN_MAX_AGE': 30, # Bağlantı ömrü (saniye cinsinden)
#                 "TEST": {
#                     "NAME": "aridb_test",
#                 },
#             }
#     }

_pool_options = {
    'min_size': 3,
    'max_size': 40,
    'max_waiting': 20,
    'max_lifetime': 300,
    'max_idle': 300,
    'reconnect_timeout': 5,
    'num_workers': 1,
}

if DB_TEST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',
            'USER': 'postgres',
            'PASSWORD': 'postgres',
            'HOST': 'db',
            'PORT': '',
            #'CONN_MAX_AGE': None,
            'OPTIONS': {'pool': _pool_options},
            'TEST': {
                'NAME': 'marswidedb_test',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': str(os.getenv('PG_DB')),
            'USER': str(os.getenv('PG_USER')),
            'PASSWORD': str(os.getenv('PG_PASSWORD')),
            'HOST': 'db',
            'PORT': '',
            #'CONN_MAX_AGE': None,
            'OPTIONS': {'pool': _pool_options},
            'TEST': {
                'NAME': 'aridb_test',
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600
MAX_UPLOAD_SIZE = 1 * 1024 * 1024

SECURE_BROWSER_XSS_FILTER = True

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

USE_S3 = config('USE_S3', cast = bool, default = False)

if USE_S3:
    AWS_ACCESS_KEY_ID=str(os.getenv('AWS_ACCESS_KEY_ID'))
    AWS_SECRET_ACCESS_KEY=str(os.getenv('AWS_SECRET_ACCESS_KEY'))
    AWS_STORAGE_BUCKET_NAME="michoapp-bucket"
    AWS_S3_REGION_NAME= 'eu-central-1'
    AWS_DEFAULT_ACL= None
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    DEFAULT_FILE_STORAGE= 'core.settings.s3utils.PublicMediaStorage'
    STATICFILES_STORAGE= 'core.settings.s3utils.StaticStorage'
    
    STATIC_LOCATION = 'static'
    PUBLIC_MEDIA_LOCATION= "media"
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{STATIC_LOCATION}/'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{PUBLIC_MEDIA_LOCATION}/'
else:
    STATIC_URL = "/staticfiles/"
    STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# auth

AUTH_USER_MODEL = 'users.User'



# Rest Framework

REST_FRAMEWORK = {
    # 'DATE_INPUT_FORMATS': "%d %b %Y",
    'DATE_FORMAT': "%d.%m.%Y",
    'DATETIME_FORMAT': "%d.%m.%Y %H:%M",
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework_datatables.filters.DatatablesFilterBackend',
        'rest_framework_datatables_editor.filters.DatatablesFilterBackend'
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
        'rest_framework_datatables_editor.renderers.DatatablesRenderer'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables_editor.pagination.DatatablesPageNumberPagination',
    'PAGE_SIZE': 200,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',  # anonim kullanıcılar için limit
        'rest_framework.throttling.UserRateThrottle',  # giriş yapmış kullanıcılar için limit
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/second',  # anonim kullanıcılar için limit
        'user': '20/second',  # kullanıcı başına günlük limit
    }
}


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

# Celery

CELERY_BROKER_URL = 'amqp://guest:guest@rabbitmq:5672//' # Rabbitmq için
#CELERY_BROKER_URL = 'redis://redis:6379/0' # Redis için

CELERY_TIMEZONE = "Europe/Istanbul"
CELERY_ENABLE_UTC = False
#CELERY_TASK_TRACK_STARTED = True
#CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'django-cache'

CELERY_BROKER_CONNECTION_HEARTBEAT = 60  # saniye
CELERY_BROKER_CONNECTION_RETRY = True

CELERY_RESULT_EXTENDED = True

# # Celery restart olduğunda schedule task'ların hemen çalışmaması için:
# CELERY_BEAT_SYNC_EVERY = 1  # Django Celery Beat için
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
# CELERY_BEAT_SYNC_SECONDS = 60  # (isteğe bağlı, default 60)

# CELERY_BEAT_SCHEDULER_MAX_INTERVAL = 60  # Scheduler'ın en fazla 60 saniyede bir kontrol etmesini sağlar

# # Celery'de restart sonrası scheduled task'ların hemen tetiklenmemesi için:
# CELERY_BEAT_SCHEDULE_FILENAME = None  # Scheduler state dosyası tutulmaz, sadece DB kullanılır

if not DEBUG:
    CELERY_BEAT_SCHEDULE = {
        "fetch-finmaks-bank-accounts-task": {
            "task": "finance.tasks.fetch_finmaks_bank_accounts",
            "schedule": crontab(minute="*/5"),
            "args": [2],
        },
        "fetch-finmaks-transactions-task": {
            "task": "finance.tasks.fetch_finmaks_transactions",
            "schedule": crontab(minute="*/5"),
            "args": [2],
        },
        "update-finekra-bank-accounts-task": {
            "task": "finance.tasks.update_finekra_bank_accounts",
            "schedule": crontab(minute="*/5"),
            "args": [2],
        },
        "fetch-data-from-leaseflex-task": {
            "task": "common.tasks.fetch_data_from_leaseflex",
            "schedule": crontab(minute=0),
            "args": [2],
        },
        "fetch-big-data-from-leaseflex-task": {
            "task": "common.tasks.fetch_big_data_from_leaseflex",
            "schedule": crontab(minute=0, hour='0,2,4,6,8,10,12,14,16,18,20,22'),
            "args": [2],
        },
        "fetch-very-big-data-from-leaseflex-task": {
            "task": "common.tasks.fetch_very_big_data_from_leaseflex",
            "schedule": crontab(minute=0, hour='1,3,5,7,9,11,13,15,17,19,21,23'),
            "args": [2],
        },
        "fetch-data-for-daily-services-task": {
            "task": "common.tasks.fetch_data_for_daily_services",
            "schedule": crontab(minute=0, hour='4'),
            "args": [2],
        },
        "fetch-big-data-for-daily-services-task": {
            "task": "common.tasks.fetch_big_data_for_daily_services",
            "schedule": crontab(minute=0, hour='1'),
            "args": [2],
        },
        "add_finmaks_bank_account_daily_record-task": {
            "task": "finance.tasks.add_finmaks_bank_account_daily_record",
            "schedule": crontab(minute=59, hour='23'),
            "args": [2],
        },
        "set_daily_morning_task": {
            "task": "finance.tasks.set_bank_activities_date",
            "schedule": crontab(minute=0, hour='7'),
            "args": [2],
        },
    }
else:
    CELERY_BEAT_SCHEDULE = {
        # "fetch-finmaks-bank-accounts-task": {
        #     "task": "finance.tasks.fetch_finmaks_bank_accounts",
        #     "schedule": crontab(minute="*/5"),
        #     "args": [2],
        # },
        # "fetch-finmaks-transactions-task": {
        #     "task": "finance.tasks.fetch_finmaks_transactions",
        #     "schedule": crontab(minute="*/5"),
        #     "args": [2],
        # },
    }

# Proxy

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Caches

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'qr-code': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'qr-code-cache',
        'TIMEOUT': 3600
    },
    "select2": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis:db:6380/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    },
    'staticfiles': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'staticfiles-filehashes'
    }
}

# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": True,
    "formatters": {
        "verbose": {
            "format": "{levelname} - {asctime} - {module} - {process:d} - {thread:d} - {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/core/debug.log"),
            "formatter": "verbose",
            "when" : "midnight",
            "interval" : 1,
            "backupCount" : 7,
        },
        "celery_file": {
            "level": "INFO",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "logs/celery/celery.log"),
            "formatter": "verbose",
            "when" : "midnight",
            "interval" : 1,
            "backupCount" : 7,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["file"],
            "level": "INFO",
            "propagate": True,
        },
        'channels': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'celery': {
            'handlers': ['celery_file'],
            'level': 'INFO',
            'propagate': True,
        },
        "django_auth_ldap": {
            "handlers": ["file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Maintenance

MAINTENANCE_MODE = config('MAINTENANCE_MODE', cast = bool, default = False)

# Cors for react
CORS_ALLOW_CREDENTIALS = True
#CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if os.getenv("CORS_ALLOWED_ORIGINS", "") else []
CORS_EXPOSE_HEADERS = ["Content-Disposition"] #????

CSRF_COOKIE_HTTPONLY = True
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if os.getenv("CSRF_TRUSTED_ORIGINS", "") else []

SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE")  # veya 'Lax' ya da 'Strict'
SESSION_COOKIE_SECURE = os.getenv("SESSION_COOKIE_SECURE")

# session
# SESSION_COOKIE_AGE = 10
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# CORS_ALLOW_CREDENTIALS = True
# CORS_ORIGIN_ALLOW_ALL = True
# CSRF_TRUSTED_ORIGINS = ['http://localhost:3000']

# Ckeditor

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # Kullanılacak araç çubuğu
        'height': 300,
        'width': '100%',
        'removePlugins': 'stylesheetparser',  # İstenmeyen özellikleri kaldırabilirsiniz
        'extraPlugins': 'codesnippet',  # Ek özellikler ekleyebilirsiniz
    },
}

# Select2

SELECT2_CACHE_BACKEND = "select2"

# Iframe

X_FRAME_OPTIONS = 'SAMEORIGIN'

# Template

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

# Access

os.environ['IP'] = str(os.getenv('IP'))

# Email

EMAIL_BACKEND = str(os.getenv('EMAIL_BACKEND'))
EMAIL_HOST = str(os.getenv('EMAIL_HOST'))
EMAIL_PORT = int(os.getenv('EMAIL_PORT'))
EMAIL_USE_TLS = bool(os.getenv('EMAIL_USE_TLS'))
EMAIL_HOST_USER = str(os.getenv('EMAIL_HOST_USER'))
EMAIL_HOST_PASSWORD = str(os.getenv('EMAIL_HOST_PASSWORD'))
DEFAULT_FROM_EMAIL = str(os.getenv('DEFAULT_FROM_EMAIL'))

SETROW_API_KEY = str(os.getenv('SETROW_API_KEY'))

if not DEBUG:
    THIRD_PERSON_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr','arzu.sasmazer@arileasing.com.tr']
    THIRD_PERSON_DOCUMENT_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr','operasyon@arileasing.com.tr','cem.disci@arileasing.com.tr']
    THIRD_PERSON_CLEARED_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr','finansman@arileasing.com.tr','arzu.akdemir@arileasing.com.tr']
    IGNORED_PARTNER_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr','arzu.sasmazer@arileasing.com.tr']
else:
    THIRD_PERSON_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr']
    THIRD_PERSON_DOCUMENT_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr']
    THIRD_PERSON_CLEARED_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr']
    IGNORED_PARTNER_EMAIL_LIST = ['koray.zorlu@arileasing.com.tr']

# Domain

BACKEND_URL = str(os.getenv('BACKEND_URL'))
FRONTEND_URL = str(os.getenv('FRONTEND_URL'))

# GeoIP

GEOIP_PATH = os.path.join(BASE_DIR, 'geoip')

# LDAP

AUTH_LDAP_SERVER_URI = "ldap://192.168.82.45:389"

AUTH_LDAP_BIND_DN = "sophos.central@arileasing.local"
AUTH_LDAP_BIND_PASSWORD = "Nowayout5057.*"

AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "OU=ARI,DC=arileasing,DC=local",
    ldap.SCOPE_SUBTREE,
    "(sAMAccountName=%(user)s)"
)

AUTH_LDAP_USER_ATTR_MAP = {
    "username": "sAMAccountName",
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

AUTH_LDAP_ALWAYS_UPDATE_USER = True
AUTH_LDAP_CREATE_USERS = True

AUTHENTICATION_BACKENDS = [
    'users.backends.CustomLDAPBackend',
    'django.contrib.auth.backends.ModelBackend',  # local admin erişimi için
]

import logging
import pprint

logger = logging.getLogger('django_auth_ldap')
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)

# Leaseflex Server
ARI_SERVER = os.getenv('ARI_SERVER','')
ARI_DATABASE = os.getenv('ARI_DATABASE','')
ARI_USERNAME = os.getenv('ARI_USERNAME','')
ARI_PASSWORD = os.getenv('ARI_PASSWORD','')
ARI_CONNECTION_STRING = f'''
    DRIVER={{ODBC Driver 18 for SQL Server}};
    SERVER={ARI_SERVER};
    DATABASE={ARI_DATABASE};
    UID={ARI_USERNAME};
    PWD={ARI_PASSWORD};
    Provider=SQLNCLI11;
    Integrated Security=SSPI;
    Persist Security Info=False;
    Initial Catalog=MASTER;
    TrustServerCertificate=yes;
'''

# Finmaks
FINMAKS_USERNAME = os.getenv('FINMAKS_USERNAME','')
FINMAKS_PASSWORD = os.getenv('FINMAKS_PASSWORD','')
FINMAKS_INSTITUTION_CODE = os.getenv('FINMAKS_INSTITUTION_CODE','')
FINMAKS_INSTITUTION_ID = os.getenv('FINMAKS_INSTITUTION_ID',0)

# Sanction Scanner
if not DEBUG:
    SANCTION_SCANNER_USERNAME = os.getenv('SANCTION_SCANNER_USERNAME','')
    SANCTION_SCANNER_PASSWORD = os.getenv('SANCTION_SCANNER_PASSWORD','')
    SANCTION_SCANNER_URL = 'https://api.sanctionscanner.com'
else:
    SANCTION_SCANNER_USERNAME = os.getenv('SANCTION_SCANNER_TEST_USERNAME','')
    SANCTION_SCANNER_PASSWORD = os.getenv('SANCTION_SCANNER_TEST_PASSWORD','')
    SANCTION_SCANNER_URL = 'https://sandbox-api.sanctionscanner.com'

# AI
AI_CLIENT = ollama.Client(host="http://192.168.81.5:11434")

# vpos
VPOS_VALIDATION_KEY = os.getenv('VPOS_VALIDATION_KEY','')

# contract form
CONTRACT_FORM_VALIDATION_KEY = os.getenv('CONTRACT_FORM_VALIDATION_KEY','')

# Sentry
if not DEBUG:
    sentry_sdk.init(
        dsn="https://bf1b38ebd9e1b207370a1e2a9f666596@o4511494864961536.ingest.de.sentry.io/4511494867386448",
        # Add data like request headers and IP for users,
        # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
        send_default_pii=True,
    )

# Agent
AGENT_SECRET_TOKEN = os.getenv('AGENT_SECRET_TOKEN','')