# Generated by Django 5.1.4 on 2025-12-15 12:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('stock_code_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Stock Code ID')),
                ('stock_code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Stock Code')),
                ('stock_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Stock Name')),
                ('item_group_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item Group ID')),
                ('item_group_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item Group Code')),
                ('item_group_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Item Group Name')),
                ('item_group_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item Group Type')),
                ('fixed_asset_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fixed Asset Group')),
                ('explanation', models.CharField(blank=True, max_length=250, null=True, verbose_name='Explanation')),
                ('item_group_type_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Item Group Type ID')),
                ('bddk_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='BDDK Code')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='companies.company')),
            ],
        ),
    ]
