# Generated by Django 5.1.4 on 2025-12-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fixed_asset_group',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fixed Asset Group'),
        ),
    ]
