# Generated by Django 5.1.4 on 2025-12-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_fixed_asset_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bddk_code',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='BDDK Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='fixed_asset_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Fixed Asset Group'),
        ),
    ]
