# Generated by Django 5.1.4 on 2025-12-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_bddk_code_alter_item_fixed_asset_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_group_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Group Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Group Type'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group_type_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Group Type ID'),
        ),
    ]
