# Generated by Django 5.1.4 on 2025-12-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_item_item_group_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fixed_asset_group',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Fixed Asset Group'),
        ),
    ]
