# Generated by Django 5.1.4 on 2025-12-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_item_fixed_asset_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_group_type',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Item Group Type'),
        ),
    ]
