# Generated by Django 5.1.4 on 2025-12-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_item_item_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_group_code',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Item Group Code'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_group_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Group Type'),
        ),
    ]
