SELECT *,
    p.PROJECT_NAME,
    b.BLOCK_NO
FROM
    RPR_PROJECT_FREE_PART fp
    LEFT JOIN RPR_PROJECT_BLOCK_LIST b (NOLOCK) ON fp.BLOCK_ID = b.BLOCK_ID
    LEFT JOIN RPR_PROJECT_LIST p ON fp.PROJECT_ID = p.PROJECT_ID
WHERE
    b.BLOCK_NO = 'A36'
    AND fp.FREE_PART_NO = '07'
