# Generated by Django 5.1.4 on 2025-10-17 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0036_partner_is_commercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('packet_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Packet ID')),
                ('message_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Message ID')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference ID')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='Send Date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('phone_number', models.CharField(blank=True, max_length=140, null=True, verbose_name='Phone Number')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smss', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_smss', to='partners.partner')),
            ],
        ),
    ]
