# Generated by Django 5.1.4 on 2025-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='category',
            field=models.CharField(blank=True, choices=[('default', 'Standart'), ('risk', 'Vadesi Geçmiş'), ('to_warned', 'İhtar Çekilecek'), ('warned', 'İhtar Çekilen'), ('to_terminated', 'Fesih Edilecek'), ('today_payment', 'Bugün Ödemesi Olan'), ('tomorrow_payment', 'Yarın Ödemesi Olan')], default='0', max_length=25, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='sms',
            name='error_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Error Code'),
        ),
        migrations.AddField(
            model_name='sms',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Reason'),
        ),
        migrations.AddField(
            model_name='sms',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'İletildi'), ('1', 'İletilemedi'), ('2', 'Beklemede')], default='0', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
