# Generated by Django 5.1.4 on 2025-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_sms_category_sms_error_code_sms_reason_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='size',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Size'),
        ),
    ]
