# Generated by Django 5.1.4 on 2025-10-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_sms_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'İletilemedi'), ('1', 'İletildi'), ('2', 'Beklemede')], default='0', max_length=25, null=True, verbose_name='Status'),
        ),
    ]
