# Generated by Django 5.1.4 on 2026-04-27 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_emailreceiver_email'),
        ('companies', '0005_usercompany_display_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SetrowEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('send_id', models.CharField(blank=True, max_length=140, null=True, verbose_name='Send ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='Email')),
                ('send_date', models.DateTimeField(blank=True, null=True, verbose_name='Send Date')),
                ('sender', models.CharField(blank=True, max_length=500, null=True, verbose_name='Sender')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setrow_emails', to='companies.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_setrow_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
