# Generated by Django 5.1.4 on 2026-04-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_setrowemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setrowemail',
            name='email',
        ),
        migrations.AddField(
            model_name='setrowemail',
            name='recipient',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Recipient'),
        ),
    ]
