# Generated by Django 5.1.4 on 2026-04-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0007_remove_setrowemail_email_setrowemail_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrowemail',
            name='status',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Status'),
        ),
    ]
