# Generated by Django 5.1.4 on 2026-04-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0008_setrowemail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrowemail',
            name='send_status',
            field=models.CharField(blank=True, choices=[('0', 'Henüz gönderilmedi'), ('1', 'Gönderildi / Okunmadı'), ('2', 'Gönderildi / Okundu'), ('3', 'Gönderilmedi / Bülten istemiyor'), ('4', 'Gönderilmedi / Hatalı adres'), ('5', 'Gönderilmedi / Junk adres')], default='0', max_length=25, null=True, verbose_name='Send Status'),
        ),
    ]
