# Generated by Django 5.1.4 on 2026-04-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0010_alter_setrowemail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='setrowemail',
            name='template',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Template'),
        ),
    ]
