# Generated by Django 5.1.4 on 2026-05-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0011_setrowemail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='category',
            field=models.CharField(blank=True, choices=[('default', 'Standart'), ('risk', 'Vadesi Geçmiş'), ('to_warned', 'İhtar Çekilecek'), ('warned', 'İhtar Çekilen'), ('to_terminated', 'Fesih Edilecek'), ('today_payment', 'Bugün Ödemesi Olan'), ('tomorrow_payment', 'Yarın Ödemesi Olan'), ('untitle_deed', 'Tapu Almayanlar')], default='0', max_length=25, null=True, verbose_name='Category'),
        ),
    ]
