# Generated by Django 5.2.14 on 2026-06-29 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0012_alter_sms_category'),
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0081_partner_nace_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('queue', models.CharField(blank=True, max_length=50, null=True, verbose_name='Queue')),
                ('phone_number', models.CharField(blank=True, max_length=140, null=True, verbose_name='Phone Number')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='companies.company')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_calls', to='partners.partner')),
            ],
        ),
    ]
