# Generated by Django 5.2.14 on 2026-06-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0013_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='agent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Agent'),
        ),
    ]
