# Generated by Django 5.2.14 on 2026-06-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0014_call_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='connected_length',
            field=models.DurationField(blank=True, null=True, verbose_name='Connected Length'),
        ),
        migrations.AddField(
            model_name='call',
            name='direction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direction'),
        ),
    ]
