# Generated by Django 5.2.14 on 2026-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0015_call_connected_length_call_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='disposition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Disposition'),
        ),
        migrations.AddField(
            model_name='call',
            name='verdict',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Verdict'),
        ),
    ]
