# Generated by Django 5.2.14 on 2026-09-04 08:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0016_call_disposition_call_verdict'),
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Message At')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('direction', models.CharField(choices=[('in', 'Gelen'), ('out', 'Giden')], max_length=10)),
                ('message_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Message Type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('wa_message_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp Message ID')),
                ('status', models.CharField(blank=True, default='sent', max_length=50, null=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whats_app_messages', to='companies.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_whatsapp_messages', to='communication.whatsappcontact')),
            ],
        ),
    ]
