# Generated by Django 5.2.14 on 2026-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0017_whatsappcontact_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcontact',
            name='wa_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp ID'),
        ),
    ]
