# Generated by Django 5.2.14 on 2026-09-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0018_whatsappcontact_wa_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Message Time'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Text'),
        ),
    ]
