SELECT lop.OperationProjectId,
    lop.OperationProjectCode,
    lop.ContractHeaderCode,
    lop.TypeName,
    lop.VatRate,
    lop.ActivationDate,
    lop.RiskIncludingTypeName,
    l.RiskIncludingLastUpdateDate AS RiskIncludingLastUpdateDate,
    lop.CurrencyCode,
    lop.CustomerBaseCost,
    lop.PaymentCount,
    lop.AnnualRate,
    lop.OperationBaseIRR,
    lop.SubStatuteName,
    lop.LeasingTypeName,
    lop.ApplicationID,
    lop.IS_LAST_PROJECT,
    lop.CurrentRequest
FROM LeasingOperationProjectList lop
LEFT JOIN LeasingOperationProject l ON lop.OperationProjectId = l.OperationProjectId