SELECT OperationProjectId,
    OperationProjectCode,
    ContractHeaderCode,
    TypeName,
    VatRate,
    ActivationDate,
    RiskIncludingTypeName,
    CurrencyCode,
    CustomerBaseCost,
    PaymentCount,
    AnnualRate,
    OperationBaseIRR,
    SubStatuteName,
    LeasingTypeName,
    ApplicationID,
    IS_LAST_PROJECT,
    CurrentRequest
FROM LeasingOperationProjectList