SELECT OPERATIONPROJECTID,
    SequenceNo,
    PAYMENTDATE,
    VATRATE,
    VATAMOUNT,
    PAYMENT,
    TOTALPAYMENTAMOUNT,
    PRINCIPALDISPLAY,
    INTERESTDISPLAY,
    LeaseType
FROM LOPPAYMENTDUELISTFORARI
WHERE OPERATIONPROJECTID = '58419'