# Generated by Django 5.1.4 on 2025-08-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0039_alter_bankactivitylease_processed_amount'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='before_total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Before Total Payment'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_purchase_payments', to='leasing.lease'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='purchasing',
            field=models.IntegerField(default=0, verbose_name='Purchasing'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='total_contract_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total contract Amount'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='total_vendor_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Vendor Payment'),
        ),
    ]
