# Generated by Django 5.1.4 on 2025-08-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchasepayment_before_total_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='after_total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='After Total Payment'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='lease_payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Lease Payment Amount'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='managing_expense',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='After Total Payment'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='next_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Next Payment'),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='vendor_payment_with_report_date',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Vendor Payment With Report Date'),
        ),
    ]
