# Generated by Django 5.1.4 on 2025-08-20 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_exportprocess_export_url'),
        ('companies', '0005_usercompany_display_currency'),
        ('leasing', '0041_lease_is_credit'),
        ('partners', '0033_alter_partner_types'),
        ('purchasing', '0003_purchasepayment_after_total_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('document_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Document ID')),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('document_number', models.CharField(blank=True, max_length=140, null=True, verbose_name='Document Number')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Document Date')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Vat Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Amount')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Exchange Rate')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_documents', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_purchase_documents', to='common.currency')),
                ('lease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_purchase_documents', to='leasing.lease')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_purchase_documents', to='partners.partner')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_purchase_documents', to='partners.partner')),
            ],
        ),
    ]
