# Generated by Django 5.1.4 on 2025-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchasedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='document_status',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Document Status'),
        ),
    ]
