# Generated by Django 5.1.4 on 2026-04-13 08:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('purchasing', '0005_purchasedocument_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('document_line_id', models.CharField(blank=True, max_length=25, null=True, verbose_name='Document Line ID')),
                ('stock_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Stock Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Vat Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Amount')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_document_items', to='companies.company')),
                ('purchase_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_document_purchase_document_items', to='purchasing.purchasedocument')),
            ],
        ),
    ]
