# Generated by Django 5.1.4 on 2026-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0006_purchasedocumentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentitem',
            name='unit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Unit Amount'),
        ),
    ]
