# Generated by Django 5.1.4 on 2026-04-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_purchasedocumentitem_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocumentitem',
            name='c_type_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='C Type ID'),
        ),
    ]
