SELECT FullName,
        FirstName,
        SecondName,
        Surname,
        ContactCompanyName,
        CustomerCode,
        IndividualCustomerId,
        IndividualCustomerCode,
        Phone,
        Address,
        CityName,
        MainSectorId,
        TaxDepartmentName,
        CommercialTaxNo,
        TCIdentityNo,
        TaxAndTCIdentity,
        CountryCode,
        FathersName,
        BirthDate,
        Email,
        PassportNo,
        IS_TURKKEP_CUSTOMER
FROM CrmIndividualCustomerList
