# Generated by Django 5.2.14 on 2026-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttask',
            name='task_id',
        ),
        migrations.AddField(
            model_name='agenttask',
            name='agent_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Agent Name'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='lf_password',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='LF Password'),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='lf_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='LF Username'),
        ),
    ]
