# Generated by Django 5.2.14 on 2026-06-15 13:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_remove_agenttask_task_id_agenttask_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
