# Generated by Django 5.2.14 on 2026-06-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agenttask_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='agent_tasks/'),
        ),
    ]
