# Generated by Django 5.2.14 on 2026-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agenttask_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='log',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Log'),
        ),
    ]
