# Generated by Django 5.2.14 on 2026-06-23 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='KapamaDetay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_header_id', models.BigIntegerField(db_index=True)),
                ('odeme_tarihi', models.DateField(verbose_name='Ödeme Tarihi')),
                ('fatura_tarihi', models.DateField(verbose_name='Fatura Tarihi')),
                ('kapatilan_tutar', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Kapatılan Tutar')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs_kapama_detaylari', to='companies.company')),
            ],
            options={
                'verbose_name': 'KRS Kapama Detayı',
                'verbose_name_plural': 'KRS Kapama Detayları',
                'ordering': ['contract_header_id', 'fatura_tarihi'],
                'indexes': [models.Index(fields=['company', 'contract_header_id'], name='krs_kapamad_company_ee59a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='KapamaHareketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_header_id', models.BigIntegerField(db_index=True)),
                ('tarih', models.DateField()),
                ('fatura_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Fatura Tutarı')),
                ('odeme_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ödeme Tutarı')),
                ('kapatilan_fatura_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Kapatılan Fatura Tutarı')),
                ('temerrut_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Temerrüt Tutarı')),
                ('bugune_kadar_temerrut', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Bugüne Kadar Temerrüt')),
                ('odenmis_temerrut', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Ödenmiş Temerrüt')),
                ('gercek_odeme_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Gerçek Ödeme Tutarı')),
                ('protokol', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Protokol')),
                ('sentetik', models.BooleanField(default=False, help_text='Fazla ödeme nedeniyle FIFO algoritması tarafından otomatik oluşturulan satır mı', verbose_name='Sentetik')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs_kapama_hareketleri', to='companies.company')),
            ],
            options={
                'verbose_name': 'KRS Kapama Hareketi',
                'verbose_name_plural': 'KRS Kapama Hareketleri',
                'ordering': ['contract_header_id', 'tarih'],
                'indexes': [models.Index(fields=['company', 'contract_header_id', 'tarih'], name='krs_kapamah_company_2cf27f_idx')],
            },
        ),
        migrations.CreateModel(
            name='KrsTemerrutHavuz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_header_id', models.BigIntegerField(db_index=True)),
                ('rapor_tarihi', models.DateField(db_index=True, verbose_name='Rapor Tarihi')),
                ('en_eski_acik_fatura_tarihi', models.DateField(blank=True, null=True, verbose_name='En Eski Açık Fatura Tarihi')),
                ('en_eski_acik_fatura_gecikme_gun', models.IntegerField(default=0, verbose_name='Gecikme Gün Sayısı')),
                ('toplam_acik_bakiye', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Açık Bakiye')),
                ('toplam_bugune_kadar_temerrut', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Toplam Bugüne Kadar Temerrüt')),
                ('risk_grubu', models.CharField(blank=True, choices=[('grup_1', 'Grup I - Standart'), ('grup_2', 'Grup II - Yakın İzleme'), ('grup_3', 'Grup III - Tahsil İmkanı Sınırlı'), ('grup_4', 'Grup IV - Tahsili Şüpheli'), ('grup_5', 'Grup V - Zarar')], max_length=10, null=True, verbose_name='Risk Grubu')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs_temerrut_havuzu', to='companies.company')),
            ],
            options={
                'verbose_name': 'KRS Raporu',
                'verbose_name_plural': 'KRS Raporları',
                'ordering': ['-rapor_tarihi', 'contract_header_id'],
                'constraints': [models.UniqueConstraint(fields=('company', 'contract_header_id', 'rapor_tarihi'), name='unique_krs_contract_per_report_date')],
            },
        ),
    ]
