# Generated by Django 5.2.14 on 2026-06-25 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('krs', '0001_initial'),
        ('leasing', '0093_lease_signature_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('kayit_turu', models.CharField(blank=True, choices=[('CS0000', 'Başlık kaydı'), ('CS0100', 'Hesap kayıtları'), ('CS0199', 'Hesap geçmişi kaydı(Sadece ilk toplu bildirimde)'), ('CS0200', 'İsim kayıtları'), ('CS0301', 'Formatlanmamış adres kayıtları'), ('CS0400', 'Kişisel Bilgilere ilişkin kayıtlar'), ('CS0500', 'İşveren Bilgilerine İlişkin kayıtlar'), ('CS0600', 'Banka Bilgilerine İlişkin kayıtları'), ('CS9999', 'Bitiş kaydı')], max_length=25, null=True, verbose_name='Kayıt Türü')),
                ('versiyon', models.CharField(blank=True, choices=[('01', 'Finansal değişim'), ('02', 'Yeni hesap açılışı'), ('03', 'Ekkart, kefil, müşterek borçlu veya özlük, adres ve iletişim bilgileri bildirimi')], max_length=25, null=True, verbose_name='Versiyon')),
                ('uye_kodu', models.CharField(blank=True, max_length=5, null=True, verbose_name='Üye Kodu')),
                ('portfoy_kodu', models.CharField(blank=True, max_length=3, null=True, verbose_name='Portföy Kodu')),
                ('portfoy_alt_kodu', models.CharField(blank=True, max_length=2, null=True, verbose_name='Portföy Alt Kodu')),
                ('uye_adi', models.CharField(blank=True, max_length=30, null=True, verbose_name='Üye Adı')),
                ('olusturma_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Oluşturma Tarihi')),
                ('bildirim_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Bildirim Tarihi')),
                ('hesap_numarasi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Hesap Numarası')),
                ('hesapla_iliskili_kisi_sayisi', models.CharField(blank=True, max_length=1, null=True, verbose_name='Hesapla İlişkili Kişi Sayısı')),
                ('doviz_kodu', models.CharField(blank=True, max_length=3, null=True, verbose_name='Döviz Kodu')),
                ('doviz_boleni', models.CharField(blank=True, max_length=1, null=True, verbose_name='Döviz Böleni')),
                ('ozel_talimat_gostergesi', models.CharField(blank=True, max_length=2, null=True, verbose_name='Özel Talimat Göstergesi')),
                ('acilis_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Açılış Tarihi')),
                ('basvuru_referans_numarasi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Başvuru Referans Numarası')),
                ('kredi_turu', models.CharField(blank=True, choices=[('02', 'Tüketici kredisi'), ('03', 'Ev kredisi'), ('23', 'Kredi kartı'), ('26', 'Kredili mevduat'), ('50', 'Mevcut bireysel müşteri'), ('60', 'Mevcut kurumsal müşteri'), ('70', 'Portföy yönetimi'), ('61', 'Kurumsal kredi başvurusu'), ('90', 'Başvurunun yeniden sorgulanması')], max_length=25, null=True, verbose_name='Kredi Türü')),
                ('faiz_orani_gostergesi', models.CharField(blank=True, choices=[('1', 'Sabit Faiz'), ('2', 'Değişken Faiz'), ('8', 'Diğer'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Faiz Oranı Göstergesi')),
                ('kredi_kullanim_amaci', models.CharField(blank=True, choices=[('01', 'Yeni Otomobil'), ('02', 'Eski Otomobil'), ('03', 'Kamyon, Otobüs, Tır, Traktör, Ticari Araç'), ('04', 'Motorsiklet'), ('05', 'Diğer Kara Aracı'), ('06', 'Ev Eşyası (Mobilya, halı vb.)'), ('07', 'Elektronik Eşya (TV, video, müzik seti vb.)'), ('08', 'Beyaz Eşya (Buzdolabı, çamaşır makinası vb.)'), ('09', 'Giyim'), ('10', 'Seyahat'), ('11', 'Deniz Aracı'), ('12', 'Konut'), ('13', 'Borç Ödemesi'), ('14', 'Çeyiz/Evlilik'), ('15', 'Eğitim'), ('16', 'Bilgisayar'), ('17', 'Tadilat, Dekorasyon'), ('18', 'Kooperatif Ödemesi, Kira, Depozito'), ('19', 'Yatırım – Menkul Değer Alımı'), ('20', 'Sağlık'), ('21', 'Ticari Amaçlı'), ('22', 'Hobi'), ('98', 'Diğer'), ('99', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Kredi Kullanım Amacı')),
                ('teminat_gostergesi', models.CharField(blank=True, choices=[('0', 'Teminatsız'), ('1', 'Rehin'), ('2', 'Teminat/İpotek'), ('3', 'Şirket kefaleti'), ('4', 'Şahıs kefaleti'), ('8', 'Diğer teminat'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Teminat Göstergesi')),
                ('kredi_tutari', models.CharField(blank=True, max_length=9, null=True, verbose_name='Kredi Tutarı')),
                ('depozito_tutari', models.CharField(blank=True, max_length=9, null=True, verbose_name='Depozito Tutarı')),
                ('sozlesme_suresi', models.CharField(blank=True, max_length=3, null=True, verbose_name='Sözleşme Süresi')),
                ('odeme_sikligi', models.CharField(blank=True, choices=[('00', 'Haftalık'), ('01', 'Aylık'), ('02', '2 ayda bir ödeme'), ('03', '3 ayda bir ödeme'), ('04', '4 ayda bir ödeme'), ('06', '6 ayda bir ödeme'), ('12', 'Yıllık'), ('Nn', 'Her "nn" ayda bir ödeme'), ('98', 'Değişken'), ('99', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Ödeme Sıklığı')),
                ('taksit_tutari', models.CharField(blank=True, max_length=9, null=True, verbose_name='Taksit Tutarı')),
                ('son_taksit_tutari', models.CharField(blank=True, max_length=9, null=True, verbose_name='Son Taksit Tutarı')),
                ('taksit_sayisi', models.CharField(blank=True, max_length=3, null=True, verbose_name='Taksit Sayısı')),
                ('odeme_sekli', models.CharField(blank=True, choices=[('01', 'Özel Ödeme Şekli'), ('02', 'Değişken Ödeme (Overdraft/Kredi Kartı)'), ('03', 'Tahsilat öncesi müşteriyi bilgilendirme'), ('04', 'Senet'), ('05', 'Sabit Ödeme (Bireysel, Konut, ... )'), ('06', 'Nakit'), ('07', 'Banka Çeki'), ('08', 'Kredi Kartı'), ('98', 'Diğer'), ('99', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Ödeme Şekli')),
                ('kredi_limiti', models.CharField(blank=True, max_length=9, null=True, verbose_name='Kredi Limiti')),
                ('hesap_odeme_durumu', models.CharField(blank=True, choices=[('0', 'Gecikme yok'), ('1', '1 ödeme gecikmiş durumda'), ('2', '2 ödeme gecikmiş durumda'), ('3', '3 ödeme gecikmiş durumda'), ('4', '4 ödeme gecikmiş durumda'), ('5', '5 ödeme gecikmiş durumda'), ('6', '6 ödeme gecikmiş durumda'), ('8', 'İdari Takip (bu kod sadece sorgu çıktısında paylaşılır, bildirimde kabul edilmez)'), ('D', 'Hareketsiz Hesap (bu kod sistem tarafından üretilir)'), ('L', 'Kanuni Takip'), ('U', 'Sınıflandırılmamış'), ('X', 'Bilgi gelmedi, güncelleme yapılmadı (bu kod sistem tarafından üretilir)')], max_length=25, null=True, verbose_name='Hesap Ödeme Durumu')),
                ('toplam_borc_bakiyesi', models.CharField(blank=True, max_length=9, null=True, verbose_name='Toplam Borç Bakiyesi')),
                ('kredi_bakiyesi_gostergesi', models.CharField(blank=True, choices=[('0', 'Borç Bakiyesi'), ('1', 'Alacak Bakiyesi')], max_length=25, null=True, verbose_name='Kredi Bakiyesi Göstergesi')),
                ('borc_faizi_bakiyesi', models.CharField(blank=True, max_length=9, null=True, verbose_name='Borç Faizi Bakiyesi')),
                ('gecikmedeki_bakiye', models.CharField(blank=True, max_length=9, null=True, verbose_name='Gecikmedeki Bakiye')),
                ('vadesinde_yapilmayan_odeme', models.CharField(blank=True, max_length=2, null=True, verbose_name='Vadesinde Yapılmayan Ödeme')),
                ('son_odeme_tutari', models.CharField(blank=True, max_length=9, null=True, verbose_name='Son Ödeme Tutarı')),
                ('son_odeme_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Son Ödeme Tarihi')),
                ('kapanis_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Kapanış Tarihi')),
                ('kanuni_takip_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Kanuni Takip Tarihi')),
                ('tahsil_edilme_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Tahsil Edilme Tarihi')),
                ('kapanma_nedeni', models.CharField(blank=True, choices=[('01', 'Çözümlenememiş anlaşmazlık'), ('02', 'Geç ödeme alışkanlığı'), ('03', 'Müşterinin ödeme güçlüğü çekmesi'), ('04', 'Müşteriye erişilememiş'), ('05', 'Müşteri işsiz kalmış'), ('06', 'Müşteri sakat kalmış'), ('07', 'Malların el değiştirmesi'), ('08', 'Vefat etmiş'), ('09', 'Kayıp, çalıntı kredi kartı'), ('10', 'Kredi kartının müşteri tarafından iadesi'), ('11', 'Kredi kartının banka tarafından kapatılması'), ('12', 'Dolandırıcılık'), ('13', 'Potansiyel risk'), ('98', 'Diğer'), ('99', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Kapanma Nedeni')),
                ('hesabin_ozel_durumu', models.CharField(blank=True, choices=[('1', 'Zarara atıldı'), ('2', 'Vefat'), ('3', 'Taşınmış'), ('4', 'Tartışmalı'), ('5', 'Banka ile düzenleme yapılmış'), ('6', 'Müşteri İtirazı'), ('7', 'Varlık Yönetim Şirketine devir'), ('0', 'Özel durumu yok')], max_length=25, null=True, verbose_name='Hesabın Özel Durumu')),
                ('yeni_hesap_numarasi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Yeni Hesap Numarası')),
                ('kalan_taksit_bakiyesi', models.CharField(blank=True, max_length=9, null=True, verbose_name='Kalan Taksit Bakiyesi')),
                ('taksit_tarihi_gostergesi', models.CharField(blank=True, choices=[('1', 'Kredinin son ödeme tarihi olduğu göstergesi. Tüketici Kredileri ve Konut kredisi için geçerlidir')], max_length=25, null=True, verbose_name='Taksit Tarihi Göstergesi')),
                ('yeniden_yapilandirma_gostergesi', models.CharField(blank=True, choices=[(' ', 'Hiç yapılandırılmamış hesap'), ('1', 'Donuk alacaklardan yeniden yapılandırılan hesap'), ('2', 'Canlı alacaklardan yeniden yapılandırılan hesap'), ('3', 'Donuk alacaklardan yeniden sınıflandırılan hesap')], max_length=25, null=True, verbose_name='Yeniden Yapılandırma Göstergesi')),
                ('yeniden_yapilandirma_tarihi', models.CharField(blank=True, max_length=8, null=True, verbose_name='Yeniden Yapılandırma Tarihi')),
                ('tedbir_karari_gostergesi', models.CharField(blank=True, choices=[(' ', 'Mahkeme tarafından verilen kredi ödemelerinin durdurulmasına yönelik hiç bir tedbir kararı bulunmuyor.'), ('1', 'Mahkeme tarafından kredi ödemelerinin durdurulmasına yönelik verilen tedbir kararı bulunuyor.')], max_length=25, null=True, verbose_name='Tedbir Kararı Göstergesi')),
                ('kayittan_dusulen_tutar', models.CharField(blank=True, max_length=9, null=True, verbose_name='Kayıttan Düşülen Tutar')),
                ('nakit_cekim_tutari', models.CharField(blank=True, max_length=9, null=True, verbose_name='Nakit Çekim Tutarı')),
                ('gecikme_gun_sayisi', models.CharField(blank=True, max_length=2, null=True, verbose_name='Gecikme Gün Sayısı')),
                ('ekstre_odeme_orani', models.CharField(blank=True, max_length=3, null=True, verbose_name='Ekstre Ödeme Oranı')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs_reports', to='companies.company')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_krs_reports', to='leasing.lease')),
            ],
        ),
    ]
