# Generated by Django 5.2.14 on 2026-06-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0021_alter_committeeform_contract'),
        ('krs', '0002_krsreport'),
        ('leasing', '0093_lease_signature_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_krs_reports', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='krsreport',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_krs_reports', to='leasing.lease'),
        ),
    ]
