# Generated by Django 5.2.14 on 2026-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0003_krsreport_contract_alter_krsreport_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='birim_kodu',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Birim Kodu'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='sube_kodu',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Şube Kodu'),
        ),
    ]
