# Generated by Django 5.2.14 on 2026-07-15 17:17

import django.db.models.deletion
import krs.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
        ('krs', '0004_krsreport_birim_kodu_krsreport_sube_kodu'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrsReportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('label', models.CharField(blank=True, max_length=250, null=True, verbose_name='Label')),
                ('file', models.FileField(blank=True, help_text='Please upload a file.', null=True, upload_to=krs.models.krs_report_document_upload_path, verbose_name='File')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='krs_report_documents', to='companies.company')),
                ('krs_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='krs_report_krs_report_documents', to='krs.krsreport')),
            ],
        ),
    ]
