# Generated by Django 5.2.14 on 2026-07-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0005_krsreportdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krsreportdocument',
            name='krs_report',
        ),
    ]
