# Generated by Django 5.2.14 on 2026-07-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0006_remove_krsreportdocument_krs_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='krsreportdocument',
            options={'verbose_name': 'KRS Rapor Dosyası', 'verbose_name_plural': 'KRS Rapor Dosyaları'},
        ),
        migrations.AddField(
            model_name='krsreport',
            name='birinci_kimlik_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Birinci Kimlik Numarası'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='birinci_kimlik_turu',
            field=models.CharField(blank=True, choices=[('1', 'Pasaport'), ('2', 'Sürücü Belgesi'), ('3', 'Nüfus Cüzdanı'), ('4', 'Ayrılmış Alan'), ('5', 'Vergi Numarası'), ('6', 'TC Kimlik Numarası / Yabancı Kimlik Numarası'), ('7', 'KKTC Kimlik No'), ('8', 'Diğer'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Birinci Kimlik Türü'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='hesap_sahibi_turu',
            field=models.CharField(blank=True, choices=[('1', 'Esas'), ('2', 'Müşterek Borçlu'), ('3', 'Kefil'), ('4', 'Diğer Teminatın Sahibi'), ('5', 'Ek kart kullanıcısı'), ('8', 'Diğer'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Hesap Sahibi Türü'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='hesap_sahibinin_numarasi',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Hesap Sahibinin Numarası'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='ikinci_kimlik_numarasi',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='İkinci Kimlik Numarası'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='ikinci_kimlik_turu',
            field=models.CharField(blank=True, choices=[('1', 'Pasaport'), ('2', 'Sürücü Belgesi'), ('3', 'Nüfus Cüzdanı'), ('4', 'Ayrılmış Alan'), ('5', 'Vergi Numarası'), ('6', 'TC Kimlik Numarası / Yabancı Kimlik Numarası'), ('7', 'KKTC Kimlik No'), ('8', 'Diğer'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='İkinci Kimlik Türü'),
        ),
    ]
