# Generated by Django 5.2.14 on 2026-07-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0007_alter_krsreportdocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='ilk_ad_1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='İlk Ad 1'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='ilk_ad_2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='İlk Ad 2'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='soyadi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Soyadı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='soyadi_eki',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Soyadı Eki'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='uyruk',
            field=models.CharField(blank=True, choices=[('01', 'İngiltere'), ('02', 'Almanya'), ('03', 'Fransa'), ('04', 'İtalya'), ('05', 'İspanya'), ('06', 'Hollanda'), ('07', 'Yunanistan'), ('08', 'Türkiye'), ('09', 'KKTC'), ('21', 'Güney Afrika Cumhuriyeti'), ('41', 'Amerika Birleşik Devletleri'), ('42', 'Kanada'), ('43', 'Meksika'), ('44', 'Orta Amerika'), ('45', 'Güney Amerika'), ('61', 'Hindistan'), ('62', 'Iran'), ('63', 'Irak'), ('64', 'Çin'), ('65', 'Japonya'), ('81', 'Avusturalya'), ('98', 'Diğer'), ('99', 'Bilinmeyen')], max_length=2, null=True, verbose_name='Uyruk'),
        ),
    ]
