# Generated by Django 5.2.14 on 2026-07-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0008_krsreport_ilk_ad_1_krsreport_ilk_ad_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='anne_adi',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Anne Adı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='baba_adi',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Baba Adı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('1', 'Erkek'), ('2', 'Kadın')], max_length=1, null=True, verbose_name='Cinsiyet'),
        ),
    ]
