# Generated by Django 5.2.14 on 2026-07-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0009_krsreport_anne_adi_krsreport_baba_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='dogum_tarihi',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='firma_adi',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Firma Adı'),
        ),
        migrations.AlterField(
            model_name='krsreport',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('1', 'Erkek'), ('2', 'Kadın'), ('3', 'Ayrılmış Alan'), ('9', 'Bilinmiyor')], max_length=1, null=True, verbose_name='Cinsiyet'),
        ),
    ]
