# Generated by Django 5.2.14 on 2026-07-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0010_krsreport_dogum_tarihi_krsreport_firma_adi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='dogum_yeri',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Doğum Yeri'),
        ),
    ]
