# Generated by Django 5.2.14 on 2026-07-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0011_krsreport_dogum_yeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='dogum_yeri_kod',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Doğum Yeri Kod'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='kisinin_dogduru_bolge_il',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Kişinin Doğduğu Bölge/İl'),
        ),
    ]
