# Generated by Django 5.2.14 on 2026-07-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0012_krsreport_dogum_yeri_kod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='adres_tipi',
            field=models.CharField(blank=True, choices=[('1', 'Ev Adresi'), ('2', 'Posta Adresi'), ('3', 'Posta Kutusu'), ('4', 'İş Adresi'), ('8', 'Diğer'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Adres Tipi'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='adrese_tasindigi_tarih',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Adrese Taşındığı Tarih'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='adresten_ayrildigi_tarih',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Adresten Ayrıldığı Tarih'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='satir_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Satır 1'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='satir_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Satır 2'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='satir_3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Satır 3'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='satir_4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Satır 4'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='simdiki_onceki_adres_gostergesi',
            field=models.CharField(blank=True, choices=[('0', 'Şimdiki'), ('1', 'Önceki'), ('2', 'İlişkili Adres'), ('8', 'Diğer'), ('9', 'Bilinmiyor')], max_length=25, null=True, verbose_name='Şimdiki/Önceki Adres Göstergesi'),
        ),
    ]
