# Generated by Django 5.2.14 on 2026-07-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0014_krsreport_posta_kodu'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='detayli_banka_bilgileri_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Detaylı Banka Bilgileri Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='detayli_isveren_bilgileri_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Detaylı İşveren Bilgileri Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='detayli_kisisel_bilgiler_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Detaylı Kişisel Bilgiler Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='diger_para_birimine_gore_hesap_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Diğer Para Birimine göre Hesap Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='formatlanmamis_adres_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Formatlanmamış Adres Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='hesap_gecmisi_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Hesap Geçmişi Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='hesap_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Hesap Kayıtlarının Toplam Sayısı'),
        ),
        migrations.AddField(
            model_name='krsreport',
            name='isim_kayitlarinin_toplam_sayisi',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='İsim Kayıtlarının Toplam Sayısı'),
        ),
    ]
