# Generated by Django 5.2.14 on 2026-07-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krs', '0015_krsreport_detayli_banka_bilgileri_kayitlarinin_toplam_sayisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='krsreport',
            name='tarihce_duzeltme_gostergesi',
            field=models.CharField(blank=True, choices=[('0', 'Düzeltme yoktur.'), ('1', 'Geçmiş döneme ait düzeltme'), ('2', 'Bulunduğumuz ay için düzeltme')], max_length=25, null=True, verbose_name='Tarihçe Düzeltme Göstergesi'),
        ),
    ]
