# Generated by Django 5.1.4 on 2025-09-15 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('users', '0005_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='authorization', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('department', models.CharField(choices=[('admin', 'Admin'), ('bilgi_islem', 'Bilgi İşlem'), ('default', 'Default'), ('finans', 'Finans'), ('genel_mudurluk', 'Genel Müdürlük'), ('muhasebe', 'Muhasebe'), ('operasyon', 'Operasyon'), ('risk', 'Risk')], default='default', max_length=25, verbose_name='Department')),
            ],
        ),
    ]
