# Generated by Django 5.1.4 on 2026-04-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_authorization_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Position'),
        ),
    ]
