# Generated by Django 5.1.4 on 2026-04-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_authorization_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorization',
            name='position',
        ),
    ]
