# Generated by Django 5.2.14 on 2026-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_authorization_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorization',
            name='department',
            field=models.CharField(choices=[('admin', 'Admin'), ('bilgi_islem', 'Bilgi İşlem'), ('default', 'Default'), ('finans', 'Finans'), ('genel_mudurluk', 'Genel Müdürlük'), ('ic_denetim', 'İç Denetim'), ('ic_kontrol', 'İç Kontrol'), ('kredi_risk_izleme', 'Kredi Risk İzleme'), ('kredi_tahsis', 'Kredi Tahsis'), ('muhasebe', 'Muhasebe'), ('musteri_iliskileri', 'Müşteri İlişkileri'), ('musteri_temsilcisi', 'Müşteri Temsilcisi'), ('operasyon', 'Operasyon')], default='default', max_length=25, verbose_name='Department'),
        ),
    ]
