SELECT top 1000 l.RPR_QUO_ID,
    l.QUO_HEADER_ID,
    q.CRM_CUSTOMER_ID,
    l.PROJECT_NAME,
    l.BLOCK_NO,
    l.FREE_PART_NO,
    l.LAST_SUB_STATU_NAME,
    l.GROSS_SALE_AMOUNT_CURR_ID,
    l.GROSS_SALE_AMOUNT,
    l.KDV,
    l.CUSTOMER_SIGN_DATE,
    l.FREE_PART_DELIVERY_DATE,
    l.AVERAGE_RETURN_PERIOD,
    l.TIMESHARE_PERIOD
FROM RPR_QUO_LIST l
LEFT JOIN RPR_QUO q ON l.RPR_QUO_ID = q.RPR_QUO_ID
--WHERE l.QUO_HEADER_ID='91941'