SELECT TOP 1000 *,
    pb.BLOCK_NO,
    fp.FREE_PART_NO
FROM
    RPR_QUO_ITEM
LEFT JOIN RPR_FREE_PART_LIST_FOR_DET fp ON RPR_QUO_ITEM.FREE_PART_ID = fp.FREE_PART_ID
LEFT JOIN RPR_PROJECT_BLOCK_LIST pb ON RPR_QUO_ITEM.BLOCK_ID = pb.BLOCK_ID
WHERE
    --RPR_QUO_ID = 52273
    QUO_HEADER_ID = 93764