SELECT 0 AS TrnConsolideId,'' AS TrnConsolideInfo,1 AS Trn_Temp_FieldForOrder,TrnId,TrnReturnDocumentNo,TrnReturnDocumentDate,TrnDueDate,TrnDate,TrnOprContractId,TrnOprProjectId,TrnOprLeasingOperationPrjId,lopStatu.OperationProjectId 
AS 
TrnOprRevisionLOPId,TrnPostingGroupId,TrnTemplateType,TrnPostingType,TrnAmountType,TrnAmountCapital,TrnAmountInterest,TrnVATAmount,TrnAmount,TrnAmountLocal,TrnAmountCompany,lopStatu.OperationProjectCode,TrnCurrencyCode,TrnOprCustomerId,TrnAccountId,TrnAccountCode,AccName 
AS 
viewTrnAccountId,TlpHdrRateCapital,TlpHdrRateInterest,TlpHdrRateVAT,lopStatu.OperationBaseIRR,lopStatu.ActivationDate,lopStatu.RiskIncludingTypeId,lopStatu.IsRevision,lopStatu.TransferCode,lopStatu.VatRate 
AS 
TrnVATRate,lopStatu.NetFinancing,lopStatu.AdvancePaymentAmount,lopStatu.OperationBaseCost,lopStatu.TRIGGER_CALCULATED,lopStatu.TRIGGER_FIXED,TrgTriggerCode,LeasingOperationRiskIncludingType.TypeName,DefinitionName,InstitutionalCustomerStatusName,(case 
when Isnull(lopStatu.HasGuarantor,0)=1 then '' else '' end) as 
HasGuarantor,OperationProjectId,lopStatu.CurrencyId,cur.CurrencyCode AS 
TrnCurrencyCodeLease,TaxAndTCIdentity,Citizen,VendorTypeName ,0 as ExtraField  FROM TradeTransaction (NOLOCK)  LEFT 
JOIN LOPRevisionJoinMainList lopStatu (NOLOCK)  ON TrnOprLeasingOperationPrjId=lopStatu.SourceLopId AND 
TrnOprCustomerId=lopStatu.CustomerId  LEFT JOIN GeneralCurrency cur (nolock) ON lopStatu.CurrencyId=cur.CurrencyId 
LEFT JOIN TradeLopProtocolsHeader (nolock) ON TrnOprLeasingOperationPrjId=TradeLopProtocolsHeader.TlpHdrSourceLopId 
LEFT JOIN TradeAccount (nolock) ON TrnAccountId=TradeAccount.AccId LEFT JOIN TradeTriggerMergeList (nolock) ON 
TrnOprLeasingOperationPrjId=TradeTriggerMergeList.TrgSourceLopId LEFT JOIN LeasingOperationRiskIncludingType (nolock) 
ON lopStatu.RiskIncludingTypeId=LeasingOperationRiskIncludingType.TypeId LEFT JOIN FoundationStatuteMenu (nolock) ON lopStatu.LastSubStatuId=FoundationStatuteMenu.DefinitionId  LEFT JOIN QuotationProjectVendorType (nolock) ON lopStatu.VendorTypeId=QuotationProjectVendorType.VendorTypeId  LEFT JOIN CrmCustomerWithTypes (nolock) ON lopStatu.CustomerId=CrmCustomerWithTypes.CustomerId LEFT JOIN CrmCompanyGroup (nolock) ON CrmCustomerWithTypes.CompanyGroupId=CrmCompanyGroup.CompanyGroupId LEFT JOIN CrmInstitutionalCustomerStatus (nolock) ON CrmCustomerWithTypes.CustomerStatute=CrmInstitutionalCustomerStatus.InstitutionalCustomerStatusId   LEFT JOIN CrmCity (nolock) ON CrmCustomerWithTypes.CityId=CrmCity.CityId LEFT JOIN CrmRegion (nolock) ON CrmCity.REGION_ID=CrmRegion.RegionId LEFT JOIN FoundationUserUnitCity (nolock) ON CrmCity.CityId=FoundationUserUnitCity.CityId LEFT JOIN CrmCustomerRepresentativeManagerList (nolock) ON CrmCustomerWithTypes.CustomerId=CrmCustomerRepresentativeManagerList.InstitutionalCustomerId  WHERE TrnDummy=0 AND (CASE WHEN TrnIsDeleted=4 AND  lopStatu.RiskIncludingTypeId=7 AND  (SELECT lll.RiskIncludingTypeId FROM LeasingOperationProject lll (NOLOCK) WHERE lll.OperationProjectId=lopStatu.OperationProjectId)=6 THEN 3 WHEN TrnIsDeleted=4 AND  lopStatu.RiskIncludingTypeId=6 AND  (SELECT TOP 1 lll.RiskIncludingTypeId FROM LOPRevisionJoinListOutPlan lll (NOLOCK) WHERE (lll.OperationProjectId=TrnOprRevisionLOPId AND TrnOprRevisionLOPId<>0) OR (lll.OperationProjectId=TrnOprLeasingOperationPrjId AND TrnOprRevisionLOPId=0) )=7 THEN 3 ELSE TrnIsDeleted END NOT IN (6,4,2,8,1) OR (TrnIsDeleted=6 AND TrnAmount<>0)) AND TrnLayer=1 AND TrnLedgerStatu=50 AND TrnAccountType=11 AND TrnOprLeasingOperationPrjId<>0 AND TrnOprLeasingOperationPrjId IN (91952,91954,65992) AND TrnPostingType IN (115,111,112,114) AND TrnPostingType<>113  ORDER BY TrnOprCustomerId,TrnOprContractId,TrnOprProjectId,TrnOprLeasingOperationPrjId 