# Generated by Django 5.2.14 on 2026-08-05 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Real Estate Agent Name')),
                ('phone_number_1', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number 1')),
                ('phone_number_2', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone Number 2')),
                ('url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agents', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsappMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='companies.company')),
                ('real_estate_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_agent_whatsapp_messages', to='emlak.realestateagent')),
            ],
        ),
    ]
