# Generated by Django 5.2.14 on 2026-08-06 09:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='ilan_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlan No'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Text'),
        ),
    ]
