# Generated by Django 5.2.14 on 2026-09-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0002_whatsappmessage_amount_whatsappmessage_ilan_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Is Sent'),
        ),
    ]
