# Generated by Django 5.2.14 on 2026-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0003_whatsappmessage_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
    ]
