# Generated by Django 5.2.14 on 2026-09-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0004_whatsappmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='meet_date',
            field=models.DateField(blank=True, null=True, verbose_name='Meet Date'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='online_meet_date',
            field=models.DateField(blank=True, null=True, verbose_name='Online Meet Date'),
        ),
    ]
