# Generated by Django 5.2.14 on 2026-09-24 12:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0005_whatsappmessage_meet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='pesinat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Peşinat Amount'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='taksit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Taksit Amount'),
        ),
    ]
