# Generated by Django 5.2.14 on 2026-09-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0006_whatsappmessage_pesinat_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='pesinat_amount_char',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Peşinat Amount Char'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='taksit_amount_char',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Taksit Amount Char'),
        ),
    ]
