# Generated by Django 5.2.14 on 2026-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0007_whatsappmessage_pesinat_amount_char_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='amount_char',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount Char'),
        ),
    ]
