# Generated by Django 5.2.14 on 2026-09-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emlak', '0008_whatsappmessage_amount_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='emlak_amount_char',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emlak Amount Char'),
        ),
    ]
