# Generated by Django 5.1.4 on 2025-10-10 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_payment_receiver'),
        ('common', '0013_exportprocess_export_url'),
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code')),
                ('account_code_trim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code Trim')),
                ('account_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Account Name')),
                ('balance_account_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Balance Account Type')),
                ('balance_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance Debit')),
                ('balance_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance Credit')),
                ('total_debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Debit')),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Credit')),
                ('balance_debit_alternate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance Debit Alternate')),
                ('balance_credit_alternate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Balance Credit Alternate')),
                ('total_debit_alternate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Debit Alternate')),
                ('total_credit_alternate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Total Credit Alternate')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balances', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_trial_balances', to='common.currency')),
            ],
        ),
    ]
