# Generated by Django 5.1.4 on 2025-10-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_trialbalance'),
        ('partners', '0036_partner_is_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_trial_balances', to='partners.partner'),
        ),
    ]
