# Generated by Django 5.1.4 on 2025-10-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_trialbalance_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account ID'),
        ),
    ]
