# Generated by Django 5.1.4 on 2025-10-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_trialbalance_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='main_account_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Main Account Code'),
        ),
    ]
