# Generated by Django 5.1.4 on 2025-11-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_trialbalance_main_account_code'),
        ('contracts', '0014_contract_created_date_leaseflex'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_trial_balances', to='contracts.contract'),
        ),
    ]
