# Generated by Django 5.1.4 on 2026-01-02 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_trialbalance_contract'),
        ('companies', '0005_usercompany_display_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialBalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trade Transaction ID')),
                ('ledger_period', models.CharField(blank=True, max_length=25, null=True, verbose_name='Ledger Period')),
                ('transaction_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Transaction Text')),
                ('amount_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Amount Type')),
                ('local_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Local Amount')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Amount')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='Transaction Date')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_transactions', to='companies.company')),
                ('trial_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trial_balance_trial_balance_transactions', to='accounting.trialbalance')),
            ],
        ),
    ]
