# Generated by Django 5.1.4 on 2026-01-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_trialbalancetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalance',
            name='account_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Account Name'),
        ),
    ]
