# Generated by Django 5.1.4 on 2026-01-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_trialbalance_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalance',
            name='account_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='trialbalancetransaction',
            name='transaction_text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Transaction Text'),
        ),
    ]
