# Generated by Django 5.1.4 on 2026-01-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0025_alter_trialbalance_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalancetransaction',
            name='user_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='User ID'),
        ),
    ]
