# Generated by Django 5.1.4 on 2026-01-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_trialbalancetransaction_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='account_code_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code 1'),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='account_code_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code 2'),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='account_code_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code 3'),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='account_code_4',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code 4'),
        ),
        migrations.AddField(
            model_name='trialbalance',
            name='account_code_5',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Code 5'),
        ),
    ]
