# Generated by Django 5.1.4 on 2026-02-02 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_trialbalance_account_code_1_and_more'),
        ('leasing', '0074_lease_ifs_tahsilat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_invoices', to='leasing.lease'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
