# Generated by Django 5.1.4 on 2026-02-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_invoice_lease_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='trn_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Trn ID'),
        ),
    ]
