# Generated by Django 5.1.4 on 2025-06-19 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0010_alter_status_model_alter_status_name'),
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0027_alter_partner_address_alter_partner_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('customer_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Customer Type')),
                ('project', models.CharField(blank=True, max_length=250, null=True, verbose_name='Project')),
                ('block', models.CharField(blank=True, max_length=25, null=True, verbose_name='Block')),
                ('unit', models.CharField(blank=True, max_length=25, null=True, verbose_name='Unit')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='Price')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Vat')),
                ('customer_signature_date', models.DateField(blank=True, null=True, verbose_name='Customer Signature Date')),
                ('unit_delivery_date', models.DateField(blank=True, null=True, verbose_name='Unit Delivery Date')),
                ('is_tufe', models.BooleanField(default=False)),
                ('ortalama_tahsil_suresi', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Ortalama Tahsil Süresi')),
                ('devremulk', models.CharField(blank=True, max_length=25, null=True, verbose_name='Devremulk')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='StartDate')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Finish Date')),
                ('bbsn', models.CharField(blank=True, max_length=25, null=True, verbose_name='BBSN')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_quotations', to='common.currency')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_quotations', to='partners.partner')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_quotations', to='common.status')),
            ],
        ),
    ]
