# Generated by Django 5.1.4 on 2025-06-19 14:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_status_model_alter_status_name'),
        ('companies', '0005_usercompany_display_currency'),
        ('partners', '0027_alter_partner_address_alter_partner_address2'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickquotation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_quotations', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='quickquotation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_quick_quotations', to='common.currency'),
        ),
        migrations.AlterField(
            model_name='quickquotation',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner_quick_quotations', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='quickquotation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_quick_quotations', to='common.status'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code', models.CharField(max_length=25, verbose_name='Code')),
                ('kbm', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='KBM')),
                ('customer_representative', models.CharField(blank=True, max_length=140, null=True, verbose_name='Customer Representative')),
                ('kof', models.CharField(blank=True, max_length=25, null=True, verbose_name='Kof')),
                ('request_date', models.DateField(blank=True, null=True, verbose_name='Request Date')),
                ('rev_date', models.DateField(blank=True, null=True, verbose_name='Rev Date')),
                ('supplier', models.CharField(blank=True, max_length=250, null=True, verbose_name='Supplier')),
                ('project', models.CharField(blank=True, max_length=250, null=True, verbose_name='Project')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='companies.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_quotations', to='common.currency')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_quotations', to='partners.partner')),
                ('quick_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_quotation_quotations', to='quotations.quickquotation')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_quotations', to='common.status')),
            ],
        ),
    ]
