# Generated by Django 5.1.4 on 2025-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0002_alter_quickquotation_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquotation',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Quotation No'),
        ),
    ]
