# Generated by Django 5.1.4 on 2025-08-07 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_vendor_id_project_partner'),
        ('quotations', '0003_quickquotation_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquotation',
            name='project_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_quick_quotations', to='projects.project'),
        ),
    ]
