# Generated by Django 5.1.4 on 2026-05-06 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_realestate_bbsn'),
        ('quotations', '0004_quickquotation_project_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickquotation',
            name='real_estate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='real_estate_quick_quotations', to='projects.realestate'),
        ),
    ]
